// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_fpga417_top_complex_fir_Pipeline_VITIS_LOOP_132_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_bundle3_AWVALID,
        m_axi_bundle3_AWREADY,
        m_axi_bundle3_AWADDR,
        m_axi_bundle3_AWID,
        m_axi_bundle3_AWLEN,
        m_axi_bundle3_AWSIZE,
        m_axi_bundle3_AWBURST,
        m_axi_bundle3_AWLOCK,
        m_axi_bundle3_AWCACHE,
        m_axi_bundle3_AWPROT,
        m_axi_bundle3_AWQOS,
        m_axi_bundle3_AWREGION,
        m_axi_bundle3_AWUSER,
        m_axi_bundle3_WVALID,
        m_axi_bundle3_WREADY,
        m_axi_bundle3_WDATA,
        m_axi_bundle3_WSTRB,
        m_axi_bundle3_WLAST,
        m_axi_bundle3_WID,
        m_axi_bundle3_WUSER,
        m_axi_bundle3_ARVALID,
        m_axi_bundle3_ARREADY,
        m_axi_bundle3_ARADDR,
        m_axi_bundle3_ARID,
        m_axi_bundle3_ARLEN,
        m_axi_bundle3_ARSIZE,
        m_axi_bundle3_ARBURST,
        m_axi_bundle3_ARLOCK,
        m_axi_bundle3_ARCACHE,
        m_axi_bundle3_ARPROT,
        m_axi_bundle3_ARQOS,
        m_axi_bundle3_ARREGION,
        m_axi_bundle3_ARUSER,
        m_axi_bundle3_RVALID,
        m_axi_bundle3_RREADY,
        m_axi_bundle3_RDATA,
        m_axi_bundle3_RLAST,
        m_axi_bundle3_RID,
        m_axi_bundle3_RFIFONUM,
        m_axi_bundle3_RUSER,
        m_axi_bundle3_RRESP,
        m_axi_bundle3_BVALID,
        m_axi_bundle3_BREADY,
        m_axi_bundle3_BRESP,
        m_axi_bundle3_BID,
        m_axi_bundle3_BUSER,
        m_axi_bundle4_AWVALID,
        m_axi_bundle4_AWREADY,
        m_axi_bundle4_AWADDR,
        m_axi_bundle4_AWID,
        m_axi_bundle4_AWLEN,
        m_axi_bundle4_AWSIZE,
        m_axi_bundle4_AWBURST,
        m_axi_bundle4_AWLOCK,
        m_axi_bundle4_AWCACHE,
        m_axi_bundle4_AWPROT,
        m_axi_bundle4_AWQOS,
        m_axi_bundle4_AWREGION,
        m_axi_bundle4_AWUSER,
        m_axi_bundle4_WVALID,
        m_axi_bundle4_WREADY,
        m_axi_bundle4_WDATA,
        m_axi_bundle4_WSTRB,
        m_axi_bundle4_WLAST,
        m_axi_bundle4_WID,
        m_axi_bundle4_WUSER,
        m_axi_bundle4_ARVALID,
        m_axi_bundle4_ARREADY,
        m_axi_bundle4_ARADDR,
        m_axi_bundle4_ARID,
        m_axi_bundle4_ARLEN,
        m_axi_bundle4_ARSIZE,
        m_axi_bundle4_ARBURST,
        m_axi_bundle4_ARLOCK,
        m_axi_bundle4_ARCACHE,
        m_axi_bundle4_ARPROT,
        m_axi_bundle4_ARQOS,
        m_axi_bundle4_ARREGION,
        m_axi_bundle4_ARUSER,
        m_axi_bundle4_RVALID,
        m_axi_bundle4_RREADY,
        m_axi_bundle4_RDATA,
        m_axi_bundle4_RLAST,
        m_axi_bundle4_RID,
        m_axi_bundle4_RFIFONUM,
        m_axi_bundle4_RUSER,
        m_axi_bundle4_RRESP,
        m_axi_bundle4_BVALID,
        m_axi_bundle4_BREADY,
        m_axi_bundle4_BRESP,
        m_axi_bundle4_BID,
        m_axi_bundle4_BUSER,
        sext_ln132_1,
        sext_ln132,
        kernel_img_temp_V_24_out,
        kernel_img_temp_V_24_out_ap_vld,
        kernel_real_temp_V_24_out,
        kernel_real_temp_V_24_out_ap_vld,
        kernel_img_temp_V_23_out,
        kernel_img_temp_V_23_out_ap_vld,
        kernel_real_temp_V_23_out,
        kernel_real_temp_V_23_out_ap_vld,
        kernel_img_temp_V_22_out,
        kernel_img_temp_V_22_out_ap_vld,
        kernel_real_temp_V_22_out,
        kernel_real_temp_V_22_out_ap_vld,
        kernel_img_temp_V_21_out,
        kernel_img_temp_V_21_out_ap_vld,
        kernel_real_temp_V_21_out,
        kernel_real_temp_V_21_out_ap_vld,
        kernel_img_temp_V_20_out,
        kernel_img_temp_V_20_out_ap_vld,
        kernel_real_temp_V_20_out,
        kernel_real_temp_V_20_out_ap_vld,
        kernel_img_temp_V_19_out,
        kernel_img_temp_V_19_out_ap_vld,
        kernel_real_temp_V_19_out,
        kernel_real_temp_V_19_out_ap_vld,
        kernel_img_temp_V_18_out,
        kernel_img_temp_V_18_out_ap_vld,
        kernel_real_temp_V_18_out,
        kernel_real_temp_V_18_out_ap_vld,
        kernel_img_temp_V_17_out,
        kernel_img_temp_V_17_out_ap_vld,
        kernel_real_temp_V_17_out,
        kernel_real_temp_V_17_out_ap_vld,
        kernel_img_temp_V_16_out,
        kernel_img_temp_V_16_out_ap_vld,
        kernel_real_temp_V_16_out,
        kernel_real_temp_V_16_out_ap_vld,
        kernel_img_temp_V_15_out,
        kernel_img_temp_V_15_out_ap_vld,
        kernel_real_temp_V_15_out,
        kernel_real_temp_V_15_out_ap_vld,
        kernel_img_temp_V_14_out,
        kernel_img_temp_V_14_out_ap_vld,
        kernel_real_temp_V_14_out,
        kernel_real_temp_V_14_out_ap_vld,
        kernel_img_temp_V_13_out,
        kernel_img_temp_V_13_out_ap_vld,
        kernel_real_temp_V_13_out,
        kernel_real_temp_V_13_out_ap_vld,
        kernel_img_temp_V_12_out,
        kernel_img_temp_V_12_out_ap_vld,
        kernel_real_temp_V_12_out,
        kernel_real_temp_V_12_out_ap_vld,
        kernel_img_temp_V_11_out,
        kernel_img_temp_V_11_out_ap_vld,
        kernel_real_temp_V_11_out,
        kernel_real_temp_V_11_out_ap_vld,
        kernel_img_temp_V_10_out,
        kernel_img_temp_V_10_out_ap_vld,
        kernel_real_temp_V_10_out,
        kernel_real_temp_V_10_out_ap_vld,
        kernel_img_temp_V_9_out,
        kernel_img_temp_V_9_out_ap_vld,
        kernel_real_temp_V_9_out,
        kernel_real_temp_V_9_out_ap_vld,
        kernel_img_temp_V_8_out,
        kernel_img_temp_V_8_out_ap_vld,
        kernel_real_temp_V_8_out,
        kernel_real_temp_V_8_out_ap_vld,
        kernel_img_temp_V_7_out,
        kernel_img_temp_V_7_out_ap_vld,
        kernel_real_temp_V_7_out,
        kernel_real_temp_V_7_out_ap_vld,
        kernel_img_temp_V_6_out,
        kernel_img_temp_V_6_out_ap_vld,
        kernel_real_temp_V_6_out,
        kernel_real_temp_V_6_out_ap_vld,
        kernel_img_temp_V_5_out,
        kernel_img_temp_V_5_out_ap_vld,
        kernel_real_temp_V_5_out,
        kernel_real_temp_V_5_out_ap_vld,
        kernel_img_temp_V_4_out,
        kernel_img_temp_V_4_out_ap_vld,
        kernel_real_temp_V_4_out,
        kernel_real_temp_V_4_out_ap_vld,
        kernel_img_temp_V_3_out,
        kernel_img_temp_V_3_out_ap_vld,
        kernel_real_temp_V_3_out,
        kernel_real_temp_V_3_out_ap_vld,
        kernel_img_temp_V_2_out,
        kernel_img_temp_V_2_out_ap_vld,
        kernel_real_temp_V_2_out,
        kernel_real_temp_V_2_out_ap_vld,
        kernel_img_temp_V_1_out,
        kernel_img_temp_V_1_out_ap_vld,
        kernel_real_temp_V_1_out,
        kernel_real_temp_V_1_out_ap_vld,
        kernel_img_temp_V_out,
        kernel_img_temp_V_out_ap_vld,
        kernel_real_temp_V_out,
        kernel_real_temp_V_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_bundle3_AWVALID;
input   m_axi_bundle3_AWREADY;
output  [63:0] m_axi_bundle3_AWADDR;
output  [0:0] m_axi_bundle3_AWID;
output  [31:0] m_axi_bundle3_AWLEN;
output  [2:0] m_axi_bundle3_AWSIZE;
output  [1:0] m_axi_bundle3_AWBURST;
output  [1:0] m_axi_bundle3_AWLOCK;
output  [3:0] m_axi_bundle3_AWCACHE;
output  [2:0] m_axi_bundle3_AWPROT;
output  [3:0] m_axi_bundle3_AWQOS;
output  [3:0] m_axi_bundle3_AWREGION;
output  [0:0] m_axi_bundle3_AWUSER;
output   m_axi_bundle3_WVALID;
input   m_axi_bundle3_WREADY;
output  [31:0] m_axi_bundle3_WDATA;
output  [3:0] m_axi_bundle3_WSTRB;
output   m_axi_bundle3_WLAST;
output  [0:0] m_axi_bundle3_WID;
output  [0:0] m_axi_bundle3_WUSER;
output   m_axi_bundle3_ARVALID;
input   m_axi_bundle3_ARREADY;
output  [63:0] m_axi_bundle3_ARADDR;
output  [0:0] m_axi_bundle3_ARID;
output  [31:0] m_axi_bundle3_ARLEN;
output  [2:0] m_axi_bundle3_ARSIZE;
output  [1:0] m_axi_bundle3_ARBURST;
output  [1:0] m_axi_bundle3_ARLOCK;
output  [3:0] m_axi_bundle3_ARCACHE;
output  [2:0] m_axi_bundle3_ARPROT;
output  [3:0] m_axi_bundle3_ARQOS;
output  [3:0] m_axi_bundle3_ARREGION;
output  [0:0] m_axi_bundle3_ARUSER;
input   m_axi_bundle3_RVALID;
output   m_axi_bundle3_RREADY;
input  [31:0] m_axi_bundle3_RDATA;
input   m_axi_bundle3_RLAST;
input  [0:0] m_axi_bundle3_RID;
input  [8:0] m_axi_bundle3_RFIFONUM;
input  [0:0] m_axi_bundle3_RUSER;
input  [1:0] m_axi_bundle3_RRESP;
input   m_axi_bundle3_BVALID;
output   m_axi_bundle3_BREADY;
input  [1:0] m_axi_bundle3_BRESP;
input  [0:0] m_axi_bundle3_BID;
input  [0:0] m_axi_bundle3_BUSER;
output   m_axi_bundle4_AWVALID;
input   m_axi_bundle4_AWREADY;
output  [63:0] m_axi_bundle4_AWADDR;
output  [0:0] m_axi_bundle4_AWID;
output  [31:0] m_axi_bundle4_AWLEN;
output  [2:0] m_axi_bundle4_AWSIZE;
output  [1:0] m_axi_bundle4_AWBURST;
output  [1:0] m_axi_bundle4_AWLOCK;
output  [3:0] m_axi_bundle4_AWCACHE;
output  [2:0] m_axi_bundle4_AWPROT;
output  [3:0] m_axi_bundle4_AWQOS;
output  [3:0] m_axi_bundle4_AWREGION;
output  [0:0] m_axi_bundle4_AWUSER;
output   m_axi_bundle4_WVALID;
input   m_axi_bundle4_WREADY;
output  [31:0] m_axi_bundle4_WDATA;
output  [3:0] m_axi_bundle4_WSTRB;
output   m_axi_bundle4_WLAST;
output  [0:0] m_axi_bundle4_WID;
output  [0:0] m_axi_bundle4_WUSER;
output   m_axi_bundle4_ARVALID;
input   m_axi_bundle4_ARREADY;
output  [63:0] m_axi_bundle4_ARADDR;
output  [0:0] m_axi_bundle4_ARID;
output  [31:0] m_axi_bundle4_ARLEN;
output  [2:0] m_axi_bundle4_ARSIZE;
output  [1:0] m_axi_bundle4_ARBURST;
output  [1:0] m_axi_bundle4_ARLOCK;
output  [3:0] m_axi_bundle4_ARCACHE;
output  [2:0] m_axi_bundle4_ARPROT;
output  [3:0] m_axi_bundle4_ARQOS;
output  [3:0] m_axi_bundle4_ARREGION;
output  [0:0] m_axi_bundle4_ARUSER;
input   m_axi_bundle4_RVALID;
output   m_axi_bundle4_RREADY;
input  [31:0] m_axi_bundle4_RDATA;
input   m_axi_bundle4_RLAST;
input  [0:0] m_axi_bundle4_RID;
input  [8:0] m_axi_bundle4_RFIFONUM;
input  [0:0] m_axi_bundle4_RUSER;
input  [1:0] m_axi_bundle4_RRESP;
input   m_axi_bundle4_BVALID;
output   m_axi_bundle4_BREADY;
input  [1:0] m_axi_bundle4_BRESP;
input  [0:0] m_axi_bundle4_BID;
input  [0:0] m_axi_bundle4_BUSER;
input  [61:0] sext_ln132_1;
input  [61:0] sext_ln132;
output  [16:0] kernel_img_temp_V_24_out;
output   kernel_img_temp_V_24_out_ap_vld;
output  [16:0] kernel_real_temp_V_24_out;
output   kernel_real_temp_V_24_out_ap_vld;
output  [16:0] kernel_img_temp_V_23_out;
output   kernel_img_temp_V_23_out_ap_vld;
output  [16:0] kernel_real_temp_V_23_out;
output   kernel_real_temp_V_23_out_ap_vld;
output  [16:0] kernel_img_temp_V_22_out;
output   kernel_img_temp_V_22_out_ap_vld;
output  [16:0] kernel_real_temp_V_22_out;
output   kernel_real_temp_V_22_out_ap_vld;
output  [16:0] kernel_img_temp_V_21_out;
output   kernel_img_temp_V_21_out_ap_vld;
output  [16:0] kernel_real_temp_V_21_out;
output   kernel_real_temp_V_21_out_ap_vld;
output  [16:0] kernel_img_temp_V_20_out;
output   kernel_img_temp_V_20_out_ap_vld;
output  [16:0] kernel_real_temp_V_20_out;
output   kernel_real_temp_V_20_out_ap_vld;
output  [16:0] kernel_img_temp_V_19_out;
output   kernel_img_temp_V_19_out_ap_vld;
output  [16:0] kernel_real_temp_V_19_out;
output   kernel_real_temp_V_19_out_ap_vld;
output  [16:0] kernel_img_temp_V_18_out;
output   kernel_img_temp_V_18_out_ap_vld;
output  [16:0] kernel_real_temp_V_18_out;
output   kernel_real_temp_V_18_out_ap_vld;
output  [16:0] kernel_img_temp_V_17_out;
output   kernel_img_temp_V_17_out_ap_vld;
output  [16:0] kernel_real_temp_V_17_out;
output   kernel_real_temp_V_17_out_ap_vld;
output  [16:0] kernel_img_temp_V_16_out;
output   kernel_img_temp_V_16_out_ap_vld;
output  [16:0] kernel_real_temp_V_16_out;
output   kernel_real_temp_V_16_out_ap_vld;
output  [16:0] kernel_img_temp_V_15_out;
output   kernel_img_temp_V_15_out_ap_vld;
output  [16:0] kernel_real_temp_V_15_out;
output   kernel_real_temp_V_15_out_ap_vld;
output  [16:0] kernel_img_temp_V_14_out;
output   kernel_img_temp_V_14_out_ap_vld;
output  [16:0] kernel_real_temp_V_14_out;
output   kernel_real_temp_V_14_out_ap_vld;
output  [16:0] kernel_img_temp_V_13_out;
output   kernel_img_temp_V_13_out_ap_vld;
output  [16:0] kernel_real_temp_V_13_out;
output   kernel_real_temp_V_13_out_ap_vld;
output  [16:0] kernel_img_temp_V_12_out;
output   kernel_img_temp_V_12_out_ap_vld;
output  [16:0] kernel_real_temp_V_12_out;
output   kernel_real_temp_V_12_out_ap_vld;
output  [16:0] kernel_img_temp_V_11_out;
output   kernel_img_temp_V_11_out_ap_vld;
output  [16:0] kernel_real_temp_V_11_out;
output   kernel_real_temp_V_11_out_ap_vld;
output  [16:0] kernel_img_temp_V_10_out;
output   kernel_img_temp_V_10_out_ap_vld;
output  [16:0] kernel_real_temp_V_10_out;
output   kernel_real_temp_V_10_out_ap_vld;
output  [16:0] kernel_img_temp_V_9_out;
output   kernel_img_temp_V_9_out_ap_vld;
output  [16:0] kernel_real_temp_V_9_out;
output   kernel_real_temp_V_9_out_ap_vld;
output  [16:0] kernel_img_temp_V_8_out;
output   kernel_img_temp_V_8_out_ap_vld;
output  [16:0] kernel_real_temp_V_8_out;
output   kernel_real_temp_V_8_out_ap_vld;
output  [16:0] kernel_img_temp_V_7_out;
output   kernel_img_temp_V_7_out_ap_vld;
output  [16:0] kernel_real_temp_V_7_out;
output   kernel_real_temp_V_7_out_ap_vld;
output  [16:0] kernel_img_temp_V_6_out;
output   kernel_img_temp_V_6_out_ap_vld;
output  [16:0] kernel_real_temp_V_6_out;
output   kernel_real_temp_V_6_out_ap_vld;
output  [16:0] kernel_img_temp_V_5_out;
output   kernel_img_temp_V_5_out_ap_vld;
output  [16:0] kernel_real_temp_V_5_out;
output   kernel_real_temp_V_5_out_ap_vld;
output  [16:0] kernel_img_temp_V_4_out;
output   kernel_img_temp_V_4_out_ap_vld;
output  [16:0] kernel_real_temp_V_4_out;
output   kernel_real_temp_V_4_out_ap_vld;
output  [16:0] kernel_img_temp_V_3_out;
output   kernel_img_temp_V_3_out_ap_vld;
output  [16:0] kernel_real_temp_V_3_out;
output   kernel_real_temp_V_3_out_ap_vld;
output  [16:0] kernel_img_temp_V_2_out;
output   kernel_img_temp_V_2_out_ap_vld;
output  [16:0] kernel_real_temp_V_2_out;
output   kernel_real_temp_V_2_out_ap_vld;
output  [16:0] kernel_img_temp_V_1_out;
output   kernel_img_temp_V_1_out_ap_vld;
output  [16:0] kernel_real_temp_V_1_out;
output   kernel_real_temp_V_1_out_ap_vld;
output  [16:0] kernel_img_temp_V_out;
output   kernel_img_temp_V_out_ap_vld;
output  [16:0] kernel_real_temp_V_out;
output   kernel_real_temp_V_out_ap_vld;

reg ap_idle;
reg m_axi_bundle3_RREADY;
reg m_axi_bundle4_RREADY;
reg kernel_img_temp_V_24_out_ap_vld;
reg kernel_real_temp_V_24_out_ap_vld;
reg kernel_img_temp_V_23_out_ap_vld;
reg kernel_real_temp_V_23_out_ap_vld;
reg kernel_img_temp_V_22_out_ap_vld;
reg kernel_real_temp_V_22_out_ap_vld;
reg kernel_img_temp_V_21_out_ap_vld;
reg kernel_real_temp_V_21_out_ap_vld;
reg kernel_img_temp_V_20_out_ap_vld;
reg kernel_real_temp_V_20_out_ap_vld;
reg kernel_img_temp_V_19_out_ap_vld;
reg kernel_real_temp_V_19_out_ap_vld;
reg kernel_img_temp_V_18_out_ap_vld;
reg kernel_real_temp_V_18_out_ap_vld;
reg kernel_img_temp_V_17_out_ap_vld;
reg kernel_real_temp_V_17_out_ap_vld;
reg kernel_img_temp_V_16_out_ap_vld;
reg kernel_real_temp_V_16_out_ap_vld;
reg kernel_img_temp_V_15_out_ap_vld;
reg kernel_real_temp_V_15_out_ap_vld;
reg kernel_img_temp_V_14_out_ap_vld;
reg kernel_real_temp_V_14_out_ap_vld;
reg kernel_img_temp_V_13_out_ap_vld;
reg kernel_real_temp_V_13_out_ap_vld;
reg kernel_img_temp_V_12_out_ap_vld;
reg kernel_real_temp_V_12_out_ap_vld;
reg kernel_img_temp_V_11_out_ap_vld;
reg kernel_real_temp_V_11_out_ap_vld;
reg kernel_img_temp_V_10_out_ap_vld;
reg kernel_real_temp_V_10_out_ap_vld;
reg kernel_img_temp_V_9_out_ap_vld;
reg kernel_real_temp_V_9_out_ap_vld;
reg kernel_img_temp_V_8_out_ap_vld;
reg kernel_real_temp_V_8_out_ap_vld;
reg kernel_img_temp_V_7_out_ap_vld;
reg kernel_real_temp_V_7_out_ap_vld;
reg kernel_img_temp_V_6_out_ap_vld;
reg kernel_real_temp_V_6_out_ap_vld;
reg kernel_img_temp_V_5_out_ap_vld;
reg kernel_real_temp_V_5_out_ap_vld;
reg kernel_img_temp_V_4_out_ap_vld;
reg kernel_real_temp_V_4_out_ap_vld;
reg kernel_img_temp_V_3_out_ap_vld;
reg kernel_real_temp_V_3_out_ap_vld;
reg kernel_img_temp_V_2_out_ap_vld;
reg kernel_real_temp_V_2_out_ap_vld;
reg kernel_img_temp_V_1_out_ap_vld;
reg kernel_real_temp_V_1_out_ap_vld;
reg kernel_img_temp_V_out_ap_vld;
reg kernel_real_temp_V_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln132_fu_800_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    bundle4_blk_n_R;
wire    ap_block_pp0_stage0;
reg    bundle3_blk_n_R;
reg   [4:0] j_1_reg_1582;
reg    ap_block_pp0_stage0_11001;
reg   [4:0] j_fu_196;
wire   [4:0] add_ln132_fu_806_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j_1;
reg   [16:0] kernel_real_temp_V_fu_200;
wire   [16:0] trunc_ln214_fu_817_p1;
reg   [16:0] kernel_img_temp_V_fu_204;
wire   [16:0] trunc_ln214_2_fu_821_p1;
reg   [16:0] kernel_real_temp_V_1_fu_208;
reg   [16:0] kernel_img_temp_V_1_fu_212;
reg   [16:0] kernel_real_temp_V_2_fu_216;
reg   [16:0] kernel_img_temp_V_2_fu_220;
reg   [16:0] kernel_real_temp_V_3_fu_224;
reg   [16:0] kernel_img_temp_V_3_fu_228;
reg   [16:0] kernel_real_temp_V_4_fu_232;
reg   [16:0] kernel_img_temp_V_4_fu_236;
reg   [16:0] kernel_real_temp_V_5_fu_240;
reg   [16:0] kernel_img_temp_V_5_fu_244;
reg   [16:0] kernel_real_temp_V_6_fu_248;
reg   [16:0] kernel_img_temp_V_6_fu_252;
reg   [16:0] kernel_real_temp_V_7_fu_256;
reg   [16:0] kernel_img_temp_V_7_fu_260;
reg   [16:0] kernel_real_temp_V_8_fu_264;
reg   [16:0] kernel_img_temp_V_8_fu_268;
reg   [16:0] kernel_real_temp_V_9_fu_272;
reg   [16:0] kernel_img_temp_V_9_fu_276;
reg   [16:0] kernel_real_temp_V_10_fu_280;
reg   [16:0] kernel_img_temp_V_10_fu_284;
reg   [16:0] kernel_real_temp_V_11_fu_288;
reg   [16:0] kernel_img_temp_V_11_fu_292;
reg   [16:0] kernel_real_temp_V_12_fu_296;
reg   [16:0] kernel_img_temp_V_12_fu_300;
reg   [16:0] kernel_real_temp_V_13_fu_304;
reg   [16:0] kernel_img_temp_V_13_fu_308;
reg   [16:0] kernel_real_temp_V_14_fu_312;
reg   [16:0] kernel_img_temp_V_14_fu_316;
reg   [16:0] kernel_real_temp_V_15_fu_320;
reg   [16:0] kernel_img_temp_V_15_fu_324;
reg   [16:0] kernel_real_temp_V_16_fu_328;
reg   [16:0] kernel_img_temp_V_16_fu_332;
reg   [16:0] kernel_real_temp_V_17_fu_336;
reg   [16:0] kernel_img_temp_V_17_fu_340;
reg   [16:0] kernel_real_temp_V_18_fu_344;
reg   [16:0] kernel_img_temp_V_18_fu_348;
reg   [16:0] kernel_real_temp_V_19_fu_352;
reg   [16:0] kernel_img_temp_V_19_fu_356;
reg   [16:0] kernel_real_temp_V_20_fu_360;
reg   [16:0] kernel_img_temp_V_20_fu_364;
reg   [16:0] kernel_real_temp_V_21_fu_368;
reg   [16:0] kernel_img_temp_V_21_fu_372;
reg   [16:0] kernel_real_temp_V_22_fu_376;
reg   [16:0] kernel_img_temp_V_22_fu_380;
reg   [16:0] kernel_real_temp_V_23_fu_384;
reg   [16:0] kernel_img_temp_V_23_fu_388;
reg   [16:0] kernel_real_temp_V_24_fu_392;
reg   [16:0] kernel_img_temp_V_24_fu_396;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

top_fpga417_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln132_fu_800_p2 == 1'd0))) begin
            j_fu_196 <= add_ln132_fu_806_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_196 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_1_reg_1582 <= ap_sig_allocacmp_j_1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd13) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_10_fu_284 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_10_fu_280 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_11_fu_292 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_11_fu_288 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd11) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_12_fu_300 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_12_fu_296 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_13_fu_308 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_13_fu_304 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd9) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_14_fu_316 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_14_fu_312 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_15_fu_324 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_15_fu_320 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_16_fu_332 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_16_fu_328 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_17_fu_340 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_17_fu_336 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_18_fu_348 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_18_fu_344 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_19_fu_356 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_19_fu_352 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd22) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_1_fu_212 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_1_fu_208 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_20_fu_364 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_20_fu_360 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_21_fu_372 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_21_fu_368 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_22_fu_380 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_22_fu_376 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_23_fu_388 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_23_fu_384 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & ((j_1_reg_1582 == 5'd24) | ((j_1_reg_1582 == 5'd25) | ((j_1_reg_1582 == 5'd26) | ((j_1_reg_1582 == 5'd27) | ((j_1_reg_1582 == 5'd28) | ((j_1_reg_1582 == 5'd29) | ((j_1_reg_1582 == 5'd30) | (j_1_reg_1582 == 5'd31)))))))))) begin
        kernel_img_temp_V_24_fu_396 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_24_fu_392 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd21) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_2_fu_220 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_2_fu_216 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd20) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_3_fu_228 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_3_fu_224 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd19) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_4_fu_236 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_4_fu_232 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd18) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_5_fu_244 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_5_fu_240 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd17) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_6_fu_252 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_6_fu_248 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_7_fu_260 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_7_fu_256 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_8_fu_268 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_8_fu_264 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd14) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_9_fu_276 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_9_fu_272 <= trunc_ln214_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((j_1_reg_1582 == 5'd23) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_fu_204 <= trunc_ln214_2_fu_821_p1;
        kernel_real_temp_V_fu_200 <= trunc_ln214_fu_817_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_196;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        bundle3_blk_n_R = m_axi_bundle3_RVALID;
    end else begin
        bundle3_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        bundle4_blk_n_R = m_axi_bundle4_RVALID;
    end else begin
        bundle4_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_10_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_11_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_12_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_13_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_14_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_15_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_16_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_17_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_18_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_19_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_1_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_20_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_21_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_22_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_23_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_24_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_2_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_3_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_4_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_5_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_6_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_7_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_8_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_9_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_img_temp_V_out_ap_vld = 1'b1;
    end else begin
        kernel_img_temp_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_10_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_11_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_12_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_13_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_14_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_15_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_16_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_17_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_18_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_19_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_1_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_20_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_21_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_22_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_23_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_24_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_2_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_3_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_4_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_5_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_6_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_7_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_8_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_9_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln132_fu_800_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_real_temp_V_out_ap_vld = 1'b1;
    end else begin
        kernel_real_temp_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_bundle3_RREADY = 1'b1;
    end else begin
        m_axi_bundle3_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_bundle4_RREADY = 1'b1;
    end else begin
        m_axi_bundle4_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln132_fu_806_p2 = (ap_sig_allocacmp_j_1 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_bundle3_RVALID == 1'b0) | (m_axi_bundle4_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_bundle3_RVALID == 1'b0) | (m_axi_bundle4_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_bundle3_RVALID == 1'b0) | (m_axi_bundle4_RVALID == 1'b0)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((m_axi_bundle3_RVALID == 1'b0) | (m_axi_bundle4_RVALID == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln132_fu_800_p2 = ((ap_sig_allocacmp_j_1 == 5'd25) ? 1'b1 : 1'b0);

assign kernel_img_temp_V_10_out = kernel_img_temp_V_10_fu_284;

assign kernel_img_temp_V_11_out = kernel_img_temp_V_11_fu_292;

assign kernel_img_temp_V_12_out = kernel_img_temp_V_12_fu_300;

assign kernel_img_temp_V_13_out = kernel_img_temp_V_13_fu_308;

assign kernel_img_temp_V_14_out = kernel_img_temp_V_14_fu_316;

assign kernel_img_temp_V_15_out = kernel_img_temp_V_15_fu_324;

assign kernel_img_temp_V_16_out = kernel_img_temp_V_16_fu_332;

assign kernel_img_temp_V_17_out = kernel_img_temp_V_17_fu_340;

assign kernel_img_temp_V_18_out = kernel_img_temp_V_18_fu_348;

assign kernel_img_temp_V_19_out = kernel_img_temp_V_19_fu_356;

assign kernel_img_temp_V_1_out = kernel_img_temp_V_1_fu_212;

assign kernel_img_temp_V_20_out = kernel_img_temp_V_20_fu_364;

assign kernel_img_temp_V_21_out = kernel_img_temp_V_21_fu_372;

assign kernel_img_temp_V_22_out = kernel_img_temp_V_22_fu_380;

assign kernel_img_temp_V_23_out = kernel_img_temp_V_23_fu_388;

assign kernel_img_temp_V_24_out = kernel_img_temp_V_24_fu_396;

assign kernel_img_temp_V_2_out = kernel_img_temp_V_2_fu_220;

assign kernel_img_temp_V_3_out = kernel_img_temp_V_3_fu_228;

assign kernel_img_temp_V_4_out = kernel_img_temp_V_4_fu_236;

assign kernel_img_temp_V_5_out = kernel_img_temp_V_5_fu_244;

assign kernel_img_temp_V_6_out = kernel_img_temp_V_6_fu_252;

assign kernel_img_temp_V_7_out = kernel_img_temp_V_7_fu_260;

assign kernel_img_temp_V_8_out = kernel_img_temp_V_8_fu_268;

assign kernel_img_temp_V_9_out = kernel_img_temp_V_9_fu_276;

assign kernel_img_temp_V_out = kernel_img_temp_V_fu_204;

assign kernel_real_temp_V_10_out = kernel_real_temp_V_10_fu_280;

assign kernel_real_temp_V_11_out = kernel_real_temp_V_11_fu_288;

assign kernel_real_temp_V_12_out = kernel_real_temp_V_12_fu_296;

assign kernel_real_temp_V_13_out = kernel_real_temp_V_13_fu_304;

assign kernel_real_temp_V_14_out = kernel_real_temp_V_14_fu_312;

assign kernel_real_temp_V_15_out = kernel_real_temp_V_15_fu_320;

assign kernel_real_temp_V_16_out = kernel_real_temp_V_16_fu_328;

assign kernel_real_temp_V_17_out = kernel_real_temp_V_17_fu_336;

assign kernel_real_temp_V_18_out = kernel_real_temp_V_18_fu_344;

assign kernel_real_temp_V_19_out = kernel_real_temp_V_19_fu_352;

assign kernel_real_temp_V_1_out = kernel_real_temp_V_1_fu_208;

assign kernel_real_temp_V_20_out = kernel_real_temp_V_20_fu_360;

assign kernel_real_temp_V_21_out = kernel_real_temp_V_21_fu_368;

assign kernel_real_temp_V_22_out = kernel_real_temp_V_22_fu_376;

assign kernel_real_temp_V_23_out = kernel_real_temp_V_23_fu_384;

assign kernel_real_temp_V_24_out = kernel_real_temp_V_24_fu_392;

assign kernel_real_temp_V_2_out = kernel_real_temp_V_2_fu_216;

assign kernel_real_temp_V_3_out = kernel_real_temp_V_3_fu_224;

assign kernel_real_temp_V_4_out = kernel_real_temp_V_4_fu_232;

assign kernel_real_temp_V_5_out = kernel_real_temp_V_5_fu_240;

assign kernel_real_temp_V_6_out = kernel_real_temp_V_6_fu_248;

assign kernel_real_temp_V_7_out = kernel_real_temp_V_7_fu_256;

assign kernel_real_temp_V_8_out = kernel_real_temp_V_8_fu_264;

assign kernel_real_temp_V_9_out = kernel_real_temp_V_9_fu_272;

assign kernel_real_temp_V_out = kernel_real_temp_V_fu_200;

assign m_axi_bundle3_ARADDR = 64'd0;

assign m_axi_bundle3_ARBURST = 2'd0;

assign m_axi_bundle3_ARCACHE = 4'd0;

assign m_axi_bundle3_ARID = 1'd0;

assign m_axi_bundle3_ARLEN = 32'd0;

assign m_axi_bundle3_ARLOCK = 2'd0;

assign m_axi_bundle3_ARPROT = 3'd0;

assign m_axi_bundle3_ARQOS = 4'd0;

assign m_axi_bundle3_ARREGION = 4'd0;

assign m_axi_bundle3_ARSIZE = 3'd0;

assign m_axi_bundle3_ARUSER = 1'd0;

assign m_axi_bundle3_ARVALID = 1'b0;

assign m_axi_bundle3_AWADDR = 64'd0;

assign m_axi_bundle3_AWBURST = 2'd0;

assign m_axi_bundle3_AWCACHE = 4'd0;

assign m_axi_bundle3_AWID = 1'd0;

assign m_axi_bundle3_AWLEN = 32'd0;

assign m_axi_bundle3_AWLOCK = 2'd0;

assign m_axi_bundle3_AWPROT = 3'd0;

assign m_axi_bundle3_AWQOS = 4'd0;

assign m_axi_bundle3_AWREGION = 4'd0;

assign m_axi_bundle3_AWSIZE = 3'd0;

assign m_axi_bundle3_AWUSER = 1'd0;

assign m_axi_bundle3_AWVALID = 1'b0;

assign m_axi_bundle3_BREADY = 1'b0;

assign m_axi_bundle3_WDATA = 32'd0;

assign m_axi_bundle3_WID = 1'd0;

assign m_axi_bundle3_WLAST = 1'b0;

assign m_axi_bundle3_WSTRB = 4'd0;

assign m_axi_bundle3_WUSER = 1'd0;

assign m_axi_bundle3_WVALID = 1'b0;

assign m_axi_bundle4_ARADDR = 64'd0;

assign m_axi_bundle4_ARBURST = 2'd0;

assign m_axi_bundle4_ARCACHE = 4'd0;

assign m_axi_bundle4_ARID = 1'd0;

assign m_axi_bundle4_ARLEN = 32'd0;

assign m_axi_bundle4_ARLOCK = 2'd0;

assign m_axi_bundle4_ARPROT = 3'd0;

assign m_axi_bundle4_ARQOS = 4'd0;

assign m_axi_bundle4_ARREGION = 4'd0;

assign m_axi_bundle4_ARSIZE = 3'd0;

assign m_axi_bundle4_ARUSER = 1'd0;

assign m_axi_bundle4_ARVALID = 1'b0;

assign m_axi_bundle4_AWADDR = 64'd0;

assign m_axi_bundle4_AWBURST = 2'd0;

assign m_axi_bundle4_AWCACHE = 4'd0;

assign m_axi_bundle4_AWID = 1'd0;

assign m_axi_bundle4_AWLEN = 32'd0;

assign m_axi_bundle4_AWLOCK = 2'd0;

assign m_axi_bundle4_AWPROT = 3'd0;

assign m_axi_bundle4_AWQOS = 4'd0;

assign m_axi_bundle4_AWREGION = 4'd0;

assign m_axi_bundle4_AWSIZE = 3'd0;

assign m_axi_bundle4_AWUSER = 1'd0;

assign m_axi_bundle4_AWVALID = 1'b0;

assign m_axi_bundle4_BREADY = 1'b0;

assign m_axi_bundle4_WDATA = 32'd0;

assign m_axi_bundle4_WID = 1'd0;

assign m_axi_bundle4_WLAST = 1'b0;

assign m_axi_bundle4_WSTRB = 4'd0;

assign m_axi_bundle4_WUSER = 1'd0;

assign m_axi_bundle4_WVALID = 1'b0;

assign trunc_ln214_2_fu_821_p1 = m_axi_bundle4_RDATA[16:0];

assign trunc_ln214_fu_817_p1 = m_axi_bundle3_RDATA[16:0];

endmodule //top_fpga417_top_complex_fir_Pipeline_VITIS_LOOP_132_1
