// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_fpga417_top_fpga417,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=18274,HLS_SYN_LUT=16994,HLS_VERSION=2022_2}" *)

module top_fpga417 (
        s_axi_bundle8_AWVALID,
        s_axi_bundle8_AWREADY,
        s_axi_bundle8_AWADDR,
        s_axi_bundle8_WVALID,
        s_axi_bundle8_WREADY,
        s_axi_bundle8_WDATA,
        s_axi_bundle8_WSTRB,
        s_axi_bundle8_ARVALID,
        s_axi_bundle8_ARREADY,
        s_axi_bundle8_ARADDR,
        s_axi_bundle8_RVALID,
        s_axi_bundle8_RREADY,
        s_axi_bundle8_RDATA,
        s_axi_bundle8_RRESP,
        s_axi_bundle8_BVALID,
        s_axi_bundle8_BREADY,
        s_axi_bundle8_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        m_axi_bundle1_AWVALID,
        m_axi_bundle1_AWREADY,
        m_axi_bundle1_AWADDR,
        m_axi_bundle1_AWID,
        m_axi_bundle1_AWLEN,
        m_axi_bundle1_AWSIZE,
        m_axi_bundle1_AWBURST,
        m_axi_bundle1_AWLOCK,
        m_axi_bundle1_AWCACHE,
        m_axi_bundle1_AWPROT,
        m_axi_bundle1_AWQOS,
        m_axi_bundle1_AWREGION,
        m_axi_bundle1_AWUSER,
        m_axi_bundle1_WVALID,
        m_axi_bundle1_WREADY,
        m_axi_bundle1_WDATA,
        m_axi_bundle1_WSTRB,
        m_axi_bundle1_WLAST,
        m_axi_bundle1_WID,
        m_axi_bundle1_WUSER,
        m_axi_bundle1_ARVALID,
        m_axi_bundle1_ARREADY,
        m_axi_bundle1_ARADDR,
        m_axi_bundle1_ARID,
        m_axi_bundle1_ARLEN,
        m_axi_bundle1_ARSIZE,
        m_axi_bundle1_ARBURST,
        m_axi_bundle1_ARLOCK,
        m_axi_bundle1_ARCACHE,
        m_axi_bundle1_ARPROT,
        m_axi_bundle1_ARQOS,
        m_axi_bundle1_ARREGION,
        m_axi_bundle1_ARUSER,
        m_axi_bundle1_RVALID,
        m_axi_bundle1_RREADY,
        m_axi_bundle1_RDATA,
        m_axi_bundle1_RLAST,
        m_axi_bundle1_RID,
        m_axi_bundle1_RUSER,
        m_axi_bundle1_RRESP,
        m_axi_bundle1_BVALID,
        m_axi_bundle1_BREADY,
        m_axi_bundle1_BRESP,
        m_axi_bundle1_BID,
        m_axi_bundle1_BUSER,
        m_axi_bundle2_AWVALID,
        m_axi_bundle2_AWREADY,
        m_axi_bundle2_AWADDR,
        m_axi_bundle2_AWID,
        m_axi_bundle2_AWLEN,
        m_axi_bundle2_AWSIZE,
        m_axi_bundle2_AWBURST,
        m_axi_bundle2_AWLOCK,
        m_axi_bundle2_AWCACHE,
        m_axi_bundle2_AWPROT,
        m_axi_bundle2_AWQOS,
        m_axi_bundle2_AWREGION,
        m_axi_bundle2_AWUSER,
        m_axi_bundle2_WVALID,
        m_axi_bundle2_WREADY,
        m_axi_bundle2_WDATA,
        m_axi_bundle2_WSTRB,
        m_axi_bundle2_WLAST,
        m_axi_bundle2_WID,
        m_axi_bundle2_WUSER,
        m_axi_bundle2_ARVALID,
        m_axi_bundle2_ARREADY,
        m_axi_bundle2_ARADDR,
        m_axi_bundle2_ARID,
        m_axi_bundle2_ARLEN,
        m_axi_bundle2_ARSIZE,
        m_axi_bundle2_ARBURST,
        m_axi_bundle2_ARLOCK,
        m_axi_bundle2_ARCACHE,
        m_axi_bundle2_ARPROT,
        m_axi_bundle2_ARQOS,
        m_axi_bundle2_ARREGION,
        m_axi_bundle2_ARUSER,
        m_axi_bundle2_RVALID,
        m_axi_bundle2_RREADY,
        m_axi_bundle2_RDATA,
        m_axi_bundle2_RLAST,
        m_axi_bundle2_RID,
        m_axi_bundle2_RUSER,
        m_axi_bundle2_RRESP,
        m_axi_bundle2_BVALID,
        m_axi_bundle2_BREADY,
        m_axi_bundle2_BRESP,
        m_axi_bundle2_BID,
        m_axi_bundle2_BUSER,
        m_axi_bundle3_AWVALID,
        m_axi_bundle3_AWREADY,
        m_axi_bundle3_AWADDR,
        m_axi_bundle3_AWID,
        m_axi_bundle3_AWLEN,
        m_axi_bundle3_AWSIZE,
        m_axi_bundle3_AWBURST,
        m_axi_bundle3_AWLOCK,
        m_axi_bundle3_AWCACHE,
        m_axi_bundle3_AWPROT,
        m_axi_bundle3_AWQOS,
        m_axi_bundle3_AWREGION,
        m_axi_bundle3_AWUSER,
        m_axi_bundle3_WVALID,
        m_axi_bundle3_WREADY,
        m_axi_bundle3_WDATA,
        m_axi_bundle3_WSTRB,
        m_axi_bundle3_WLAST,
        m_axi_bundle3_WID,
        m_axi_bundle3_WUSER,
        m_axi_bundle3_ARVALID,
        m_axi_bundle3_ARREADY,
        m_axi_bundle3_ARADDR,
        m_axi_bundle3_ARID,
        m_axi_bundle3_ARLEN,
        m_axi_bundle3_ARSIZE,
        m_axi_bundle3_ARBURST,
        m_axi_bundle3_ARLOCK,
        m_axi_bundle3_ARCACHE,
        m_axi_bundle3_ARPROT,
        m_axi_bundle3_ARQOS,
        m_axi_bundle3_ARREGION,
        m_axi_bundle3_ARUSER,
        m_axi_bundle3_RVALID,
        m_axi_bundle3_RREADY,
        m_axi_bundle3_RDATA,
        m_axi_bundle3_RLAST,
        m_axi_bundle3_RID,
        m_axi_bundle3_RUSER,
        m_axi_bundle3_RRESP,
        m_axi_bundle3_BVALID,
        m_axi_bundle3_BREADY,
        m_axi_bundle3_BRESP,
        m_axi_bundle3_BID,
        m_axi_bundle3_BUSER,
        m_axi_bundle4_AWVALID,
        m_axi_bundle4_AWREADY,
        m_axi_bundle4_AWADDR,
        m_axi_bundle4_AWID,
        m_axi_bundle4_AWLEN,
        m_axi_bundle4_AWSIZE,
        m_axi_bundle4_AWBURST,
        m_axi_bundle4_AWLOCK,
        m_axi_bundle4_AWCACHE,
        m_axi_bundle4_AWPROT,
        m_axi_bundle4_AWQOS,
        m_axi_bundle4_AWREGION,
        m_axi_bundle4_AWUSER,
        m_axi_bundle4_WVALID,
        m_axi_bundle4_WREADY,
        m_axi_bundle4_WDATA,
        m_axi_bundle4_WSTRB,
        m_axi_bundle4_WLAST,
        m_axi_bundle4_WID,
        m_axi_bundle4_WUSER,
        m_axi_bundle4_ARVALID,
        m_axi_bundle4_ARREADY,
        m_axi_bundle4_ARADDR,
        m_axi_bundle4_ARID,
        m_axi_bundle4_ARLEN,
        m_axi_bundle4_ARSIZE,
        m_axi_bundle4_ARBURST,
        m_axi_bundle4_ARLOCK,
        m_axi_bundle4_ARCACHE,
        m_axi_bundle4_ARPROT,
        m_axi_bundle4_ARQOS,
        m_axi_bundle4_ARREGION,
        m_axi_bundle4_ARUSER,
        m_axi_bundle4_RVALID,
        m_axi_bundle4_RREADY,
        m_axi_bundle4_RDATA,
        m_axi_bundle4_RLAST,
        m_axi_bundle4_RID,
        m_axi_bundle4_RUSER,
        m_axi_bundle4_RRESP,
        m_axi_bundle4_BVALID,
        m_axi_bundle4_BREADY,
        m_axi_bundle4_BRESP,
        m_axi_bundle4_BID,
        m_axi_bundle4_BUSER,
        m_axi_bundle5_AWVALID,
        m_axi_bundle5_AWREADY,
        m_axi_bundle5_AWADDR,
        m_axi_bundle5_AWID,
        m_axi_bundle5_AWLEN,
        m_axi_bundle5_AWSIZE,
        m_axi_bundle5_AWBURST,
        m_axi_bundle5_AWLOCK,
        m_axi_bundle5_AWCACHE,
        m_axi_bundle5_AWPROT,
        m_axi_bundle5_AWQOS,
        m_axi_bundle5_AWREGION,
        m_axi_bundle5_AWUSER,
        m_axi_bundle5_WVALID,
        m_axi_bundle5_WREADY,
        m_axi_bundle5_WDATA,
        m_axi_bundle5_WSTRB,
        m_axi_bundle5_WLAST,
        m_axi_bundle5_WID,
        m_axi_bundle5_WUSER,
        m_axi_bundle5_ARVALID,
        m_axi_bundle5_ARREADY,
        m_axi_bundle5_ARADDR,
        m_axi_bundle5_ARID,
        m_axi_bundle5_ARLEN,
        m_axi_bundle5_ARSIZE,
        m_axi_bundle5_ARBURST,
        m_axi_bundle5_ARLOCK,
        m_axi_bundle5_ARCACHE,
        m_axi_bundle5_ARPROT,
        m_axi_bundle5_ARQOS,
        m_axi_bundle5_ARREGION,
        m_axi_bundle5_ARUSER,
        m_axi_bundle5_RVALID,
        m_axi_bundle5_RREADY,
        m_axi_bundle5_RDATA,
        m_axi_bundle5_RLAST,
        m_axi_bundle5_RID,
        m_axi_bundle5_RUSER,
        m_axi_bundle5_RRESP,
        m_axi_bundle5_BVALID,
        m_axi_bundle5_BREADY,
        m_axi_bundle5_BRESP,
        m_axi_bundle5_BID,
        m_axi_bundle5_BUSER,
        m_axi_bundle6_AWVALID,
        m_axi_bundle6_AWREADY,
        m_axi_bundle6_AWADDR,
        m_axi_bundle6_AWID,
        m_axi_bundle6_AWLEN,
        m_axi_bundle6_AWSIZE,
        m_axi_bundle6_AWBURST,
        m_axi_bundle6_AWLOCK,
        m_axi_bundle6_AWCACHE,
        m_axi_bundle6_AWPROT,
        m_axi_bundle6_AWQOS,
        m_axi_bundle6_AWREGION,
        m_axi_bundle6_AWUSER,
        m_axi_bundle6_WVALID,
        m_axi_bundle6_WREADY,
        m_axi_bundle6_WDATA,
        m_axi_bundle6_WSTRB,
        m_axi_bundle6_WLAST,
        m_axi_bundle6_WID,
        m_axi_bundle6_WUSER,
        m_axi_bundle6_ARVALID,
        m_axi_bundle6_ARREADY,
        m_axi_bundle6_ARADDR,
        m_axi_bundle6_ARID,
        m_axi_bundle6_ARLEN,
        m_axi_bundle6_ARSIZE,
        m_axi_bundle6_ARBURST,
        m_axi_bundle6_ARLOCK,
        m_axi_bundle6_ARCACHE,
        m_axi_bundle6_ARPROT,
        m_axi_bundle6_ARQOS,
        m_axi_bundle6_ARREGION,
        m_axi_bundle6_ARUSER,
        m_axi_bundle6_RVALID,
        m_axi_bundle6_RREADY,
        m_axi_bundle6_RDATA,
        m_axi_bundle6_RLAST,
        m_axi_bundle6_RID,
        m_axi_bundle6_RUSER,
        m_axi_bundle6_RRESP,
        m_axi_bundle6_BVALID,
        m_axi_bundle6_BREADY,
        m_axi_bundle6_BRESP,
        m_axi_bundle6_BID,
        m_axi_bundle6_BUSER,
        input_length
);

parameter    C_S_AXI_BUNDLE8_DATA_WIDTH = 32;
parameter    C_S_AXI_BUNDLE8_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_M_AXI_BUNDLE1_ID_WIDTH = 1;
parameter    C_M_AXI_BUNDLE1_ADDR_WIDTH = 64;
parameter    C_M_AXI_BUNDLE1_DATA_WIDTH = 32;
parameter    C_M_AXI_BUNDLE1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE1_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE1_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE1_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE1_USER_VALUE = 0;
parameter    C_M_AXI_BUNDLE1_PROT_VALUE = 0;
parameter    C_M_AXI_BUNDLE1_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_BUNDLE2_ID_WIDTH = 1;
parameter    C_M_AXI_BUNDLE2_ADDR_WIDTH = 64;
parameter    C_M_AXI_BUNDLE2_DATA_WIDTH = 32;
parameter    C_M_AXI_BUNDLE2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE2_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE2_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE2_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE2_USER_VALUE = 0;
parameter    C_M_AXI_BUNDLE2_PROT_VALUE = 0;
parameter    C_M_AXI_BUNDLE2_CACHE_VALUE = 3;
parameter    C_M_AXI_BUNDLE3_ID_WIDTH = 1;
parameter    C_M_AXI_BUNDLE3_ADDR_WIDTH = 64;
parameter    C_M_AXI_BUNDLE3_DATA_WIDTH = 32;
parameter    C_M_AXI_BUNDLE3_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE3_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE3_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE3_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE3_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE3_USER_VALUE = 0;
parameter    C_M_AXI_BUNDLE3_PROT_VALUE = 0;
parameter    C_M_AXI_BUNDLE3_CACHE_VALUE = 3;
parameter    C_M_AXI_BUNDLE4_ID_WIDTH = 1;
parameter    C_M_AXI_BUNDLE4_ADDR_WIDTH = 64;
parameter    C_M_AXI_BUNDLE4_DATA_WIDTH = 32;
parameter    C_M_AXI_BUNDLE4_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE4_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE4_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE4_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE4_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE4_USER_VALUE = 0;
parameter    C_M_AXI_BUNDLE4_PROT_VALUE = 0;
parameter    C_M_AXI_BUNDLE4_CACHE_VALUE = 3;
parameter    C_M_AXI_BUNDLE5_ID_WIDTH = 1;
parameter    C_M_AXI_BUNDLE5_ADDR_WIDTH = 64;
parameter    C_M_AXI_BUNDLE5_DATA_WIDTH = 32;
parameter    C_M_AXI_BUNDLE5_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE5_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE5_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE5_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE5_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE5_USER_VALUE = 0;
parameter    C_M_AXI_BUNDLE5_PROT_VALUE = 0;
parameter    C_M_AXI_BUNDLE5_CACHE_VALUE = 3;
parameter    C_M_AXI_BUNDLE6_ID_WIDTH = 1;
parameter    C_M_AXI_BUNDLE6_ADDR_WIDTH = 64;
parameter    C_M_AXI_BUNDLE6_DATA_WIDTH = 32;
parameter    C_M_AXI_BUNDLE6_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE6_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE6_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE6_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE6_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUNDLE6_USER_VALUE = 0;
parameter    C_M_AXI_BUNDLE6_PROT_VALUE = 0;
parameter    C_M_AXI_BUNDLE6_CACHE_VALUE = 3;

parameter C_S_AXI_BUNDLE8_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUNDLE1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUNDLE2_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUNDLE3_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUNDLE4_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUNDLE5_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUNDLE6_WSTRB_WIDTH = (32 / 8);

input   s_axi_bundle8_AWVALID;
output   s_axi_bundle8_AWREADY;
input  [C_S_AXI_BUNDLE8_ADDR_WIDTH - 1:0] s_axi_bundle8_AWADDR;
input   s_axi_bundle8_WVALID;
output   s_axi_bundle8_WREADY;
input  [C_S_AXI_BUNDLE8_DATA_WIDTH - 1:0] s_axi_bundle8_WDATA;
input  [C_S_AXI_BUNDLE8_WSTRB_WIDTH - 1:0] s_axi_bundle8_WSTRB;
input   s_axi_bundle8_ARVALID;
output   s_axi_bundle8_ARREADY;
input  [C_S_AXI_BUNDLE8_ADDR_WIDTH - 1:0] s_axi_bundle8_ARADDR;
output   s_axi_bundle8_RVALID;
input   s_axi_bundle8_RREADY;
output  [C_S_AXI_BUNDLE8_DATA_WIDTH - 1:0] s_axi_bundle8_RDATA;
output  [1:0] s_axi_bundle8_RRESP;
output   s_axi_bundle8_BVALID;
input   s_axi_bundle8_BREADY;
output  [1:0] s_axi_bundle8_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   m_axi_bundle1_AWVALID;
input   m_axi_bundle1_AWREADY;
output  [C_M_AXI_BUNDLE1_ADDR_WIDTH - 1:0] m_axi_bundle1_AWADDR;
output  [C_M_AXI_BUNDLE1_ID_WIDTH - 1:0] m_axi_bundle1_AWID;
output  [7:0] m_axi_bundle1_AWLEN;
output  [2:0] m_axi_bundle1_AWSIZE;
output  [1:0] m_axi_bundle1_AWBURST;
output  [1:0] m_axi_bundle1_AWLOCK;
output  [3:0] m_axi_bundle1_AWCACHE;
output  [2:0] m_axi_bundle1_AWPROT;
output  [3:0] m_axi_bundle1_AWQOS;
output  [3:0] m_axi_bundle1_AWREGION;
output  [C_M_AXI_BUNDLE1_AWUSER_WIDTH - 1:0] m_axi_bundle1_AWUSER;
output   m_axi_bundle1_WVALID;
input   m_axi_bundle1_WREADY;
output  [C_M_AXI_BUNDLE1_DATA_WIDTH - 1:0] m_axi_bundle1_WDATA;
output  [C_M_AXI_BUNDLE1_WSTRB_WIDTH - 1:0] m_axi_bundle1_WSTRB;
output   m_axi_bundle1_WLAST;
output  [C_M_AXI_BUNDLE1_ID_WIDTH - 1:0] m_axi_bundle1_WID;
output  [C_M_AXI_BUNDLE1_WUSER_WIDTH - 1:0] m_axi_bundle1_WUSER;
output   m_axi_bundle1_ARVALID;
input   m_axi_bundle1_ARREADY;
output  [C_M_AXI_BUNDLE1_ADDR_WIDTH - 1:0] m_axi_bundle1_ARADDR;
output  [C_M_AXI_BUNDLE1_ID_WIDTH - 1:0] m_axi_bundle1_ARID;
output  [7:0] m_axi_bundle1_ARLEN;
output  [2:0] m_axi_bundle1_ARSIZE;
output  [1:0] m_axi_bundle1_ARBURST;
output  [1:0] m_axi_bundle1_ARLOCK;
output  [3:0] m_axi_bundle1_ARCACHE;
output  [2:0] m_axi_bundle1_ARPROT;
output  [3:0] m_axi_bundle1_ARQOS;
output  [3:0] m_axi_bundle1_ARREGION;
output  [C_M_AXI_BUNDLE1_ARUSER_WIDTH - 1:0] m_axi_bundle1_ARUSER;
input   m_axi_bundle1_RVALID;
output   m_axi_bundle1_RREADY;
input  [C_M_AXI_BUNDLE1_DATA_WIDTH - 1:0] m_axi_bundle1_RDATA;
input   m_axi_bundle1_RLAST;
input  [C_M_AXI_BUNDLE1_ID_WIDTH - 1:0] m_axi_bundle1_RID;
input  [C_M_AXI_BUNDLE1_RUSER_WIDTH - 1:0] m_axi_bundle1_RUSER;
input  [1:0] m_axi_bundle1_RRESP;
input   m_axi_bundle1_BVALID;
output   m_axi_bundle1_BREADY;
input  [1:0] m_axi_bundle1_BRESP;
input  [C_M_AXI_BUNDLE1_ID_WIDTH - 1:0] m_axi_bundle1_BID;
input  [C_M_AXI_BUNDLE1_BUSER_WIDTH - 1:0] m_axi_bundle1_BUSER;
output   m_axi_bundle2_AWVALID;
input   m_axi_bundle2_AWREADY;
output  [C_M_AXI_BUNDLE2_ADDR_WIDTH - 1:0] m_axi_bundle2_AWADDR;
output  [C_M_AXI_BUNDLE2_ID_WIDTH - 1:0] m_axi_bundle2_AWID;
output  [7:0] m_axi_bundle2_AWLEN;
output  [2:0] m_axi_bundle2_AWSIZE;
output  [1:0] m_axi_bundle2_AWBURST;
output  [1:0] m_axi_bundle2_AWLOCK;
output  [3:0] m_axi_bundle2_AWCACHE;
output  [2:0] m_axi_bundle2_AWPROT;
output  [3:0] m_axi_bundle2_AWQOS;
output  [3:0] m_axi_bundle2_AWREGION;
output  [C_M_AXI_BUNDLE2_AWUSER_WIDTH - 1:0] m_axi_bundle2_AWUSER;
output   m_axi_bundle2_WVALID;
input   m_axi_bundle2_WREADY;
output  [C_M_AXI_BUNDLE2_DATA_WIDTH - 1:0] m_axi_bundle2_WDATA;
output  [C_M_AXI_BUNDLE2_WSTRB_WIDTH - 1:0] m_axi_bundle2_WSTRB;
output   m_axi_bundle2_WLAST;
output  [C_M_AXI_BUNDLE2_ID_WIDTH - 1:0] m_axi_bundle2_WID;
output  [C_M_AXI_BUNDLE2_WUSER_WIDTH - 1:0] m_axi_bundle2_WUSER;
output   m_axi_bundle2_ARVALID;
input   m_axi_bundle2_ARREADY;
output  [C_M_AXI_BUNDLE2_ADDR_WIDTH - 1:0] m_axi_bundle2_ARADDR;
output  [C_M_AXI_BUNDLE2_ID_WIDTH - 1:0] m_axi_bundle2_ARID;
output  [7:0] m_axi_bundle2_ARLEN;
output  [2:0] m_axi_bundle2_ARSIZE;
output  [1:0] m_axi_bundle2_ARBURST;
output  [1:0] m_axi_bundle2_ARLOCK;
output  [3:0] m_axi_bundle2_ARCACHE;
output  [2:0] m_axi_bundle2_ARPROT;
output  [3:0] m_axi_bundle2_ARQOS;
output  [3:0] m_axi_bundle2_ARREGION;
output  [C_M_AXI_BUNDLE2_ARUSER_WIDTH - 1:0] m_axi_bundle2_ARUSER;
input   m_axi_bundle2_RVALID;
output   m_axi_bundle2_RREADY;
input  [C_M_AXI_BUNDLE2_DATA_WIDTH - 1:0] m_axi_bundle2_RDATA;
input   m_axi_bundle2_RLAST;
input  [C_M_AXI_BUNDLE2_ID_WIDTH - 1:0] m_axi_bundle2_RID;
input  [C_M_AXI_BUNDLE2_RUSER_WIDTH - 1:0] m_axi_bundle2_RUSER;
input  [1:0] m_axi_bundle2_RRESP;
input   m_axi_bundle2_BVALID;
output   m_axi_bundle2_BREADY;
input  [1:0] m_axi_bundle2_BRESP;
input  [C_M_AXI_BUNDLE2_ID_WIDTH - 1:0] m_axi_bundle2_BID;
input  [C_M_AXI_BUNDLE2_BUSER_WIDTH - 1:0] m_axi_bundle2_BUSER;
output   m_axi_bundle3_AWVALID;
input   m_axi_bundle3_AWREADY;
output  [C_M_AXI_BUNDLE3_ADDR_WIDTH - 1:0] m_axi_bundle3_AWADDR;
output  [C_M_AXI_BUNDLE3_ID_WIDTH - 1:0] m_axi_bundle3_AWID;
output  [7:0] m_axi_bundle3_AWLEN;
output  [2:0] m_axi_bundle3_AWSIZE;
output  [1:0] m_axi_bundle3_AWBURST;
output  [1:0] m_axi_bundle3_AWLOCK;
output  [3:0] m_axi_bundle3_AWCACHE;
output  [2:0] m_axi_bundle3_AWPROT;
output  [3:0] m_axi_bundle3_AWQOS;
output  [3:0] m_axi_bundle3_AWREGION;
output  [C_M_AXI_BUNDLE3_AWUSER_WIDTH - 1:0] m_axi_bundle3_AWUSER;
output   m_axi_bundle3_WVALID;
input   m_axi_bundle3_WREADY;
output  [C_M_AXI_BUNDLE3_DATA_WIDTH - 1:0] m_axi_bundle3_WDATA;
output  [C_M_AXI_BUNDLE3_WSTRB_WIDTH - 1:0] m_axi_bundle3_WSTRB;
output   m_axi_bundle3_WLAST;
output  [C_M_AXI_BUNDLE3_ID_WIDTH - 1:0] m_axi_bundle3_WID;
output  [C_M_AXI_BUNDLE3_WUSER_WIDTH - 1:0] m_axi_bundle3_WUSER;
output   m_axi_bundle3_ARVALID;
input   m_axi_bundle3_ARREADY;
output  [C_M_AXI_BUNDLE3_ADDR_WIDTH - 1:0] m_axi_bundle3_ARADDR;
output  [C_M_AXI_BUNDLE3_ID_WIDTH - 1:0] m_axi_bundle3_ARID;
output  [7:0] m_axi_bundle3_ARLEN;
output  [2:0] m_axi_bundle3_ARSIZE;
output  [1:0] m_axi_bundle3_ARBURST;
output  [1:0] m_axi_bundle3_ARLOCK;
output  [3:0] m_axi_bundle3_ARCACHE;
output  [2:0] m_axi_bundle3_ARPROT;
output  [3:0] m_axi_bundle3_ARQOS;
output  [3:0] m_axi_bundle3_ARREGION;
output  [C_M_AXI_BUNDLE3_ARUSER_WIDTH - 1:0] m_axi_bundle3_ARUSER;
input   m_axi_bundle3_RVALID;
output   m_axi_bundle3_RREADY;
input  [C_M_AXI_BUNDLE3_DATA_WIDTH - 1:0] m_axi_bundle3_RDATA;
input   m_axi_bundle3_RLAST;
input  [C_M_AXI_BUNDLE3_ID_WIDTH - 1:0] m_axi_bundle3_RID;
input  [C_M_AXI_BUNDLE3_RUSER_WIDTH - 1:0] m_axi_bundle3_RUSER;
input  [1:0] m_axi_bundle3_RRESP;
input   m_axi_bundle3_BVALID;
output   m_axi_bundle3_BREADY;
input  [1:0] m_axi_bundle3_BRESP;
input  [C_M_AXI_BUNDLE3_ID_WIDTH - 1:0] m_axi_bundle3_BID;
input  [C_M_AXI_BUNDLE3_BUSER_WIDTH - 1:0] m_axi_bundle3_BUSER;
output   m_axi_bundle4_AWVALID;
input   m_axi_bundle4_AWREADY;
output  [C_M_AXI_BUNDLE4_ADDR_WIDTH - 1:0] m_axi_bundle4_AWADDR;
output  [C_M_AXI_BUNDLE4_ID_WIDTH - 1:0] m_axi_bundle4_AWID;
output  [7:0] m_axi_bundle4_AWLEN;
output  [2:0] m_axi_bundle4_AWSIZE;
output  [1:0] m_axi_bundle4_AWBURST;
output  [1:0] m_axi_bundle4_AWLOCK;
output  [3:0] m_axi_bundle4_AWCACHE;
output  [2:0] m_axi_bundle4_AWPROT;
output  [3:0] m_axi_bundle4_AWQOS;
output  [3:0] m_axi_bundle4_AWREGION;
output  [C_M_AXI_BUNDLE4_AWUSER_WIDTH - 1:0] m_axi_bundle4_AWUSER;
output   m_axi_bundle4_WVALID;
input   m_axi_bundle4_WREADY;
output  [C_M_AXI_BUNDLE4_DATA_WIDTH - 1:0] m_axi_bundle4_WDATA;
output  [C_M_AXI_BUNDLE4_WSTRB_WIDTH - 1:0] m_axi_bundle4_WSTRB;
output   m_axi_bundle4_WLAST;
output  [C_M_AXI_BUNDLE4_ID_WIDTH - 1:0] m_axi_bundle4_WID;
output  [C_M_AXI_BUNDLE4_WUSER_WIDTH - 1:0] m_axi_bundle4_WUSER;
output   m_axi_bundle4_ARVALID;
input   m_axi_bundle4_ARREADY;
output  [C_M_AXI_BUNDLE4_ADDR_WIDTH - 1:0] m_axi_bundle4_ARADDR;
output  [C_M_AXI_BUNDLE4_ID_WIDTH - 1:0] m_axi_bundle4_ARID;
output  [7:0] m_axi_bundle4_ARLEN;
output  [2:0] m_axi_bundle4_ARSIZE;
output  [1:0] m_axi_bundle4_ARBURST;
output  [1:0] m_axi_bundle4_ARLOCK;
output  [3:0] m_axi_bundle4_ARCACHE;
output  [2:0] m_axi_bundle4_ARPROT;
output  [3:0] m_axi_bundle4_ARQOS;
output  [3:0] m_axi_bundle4_ARREGION;
output  [C_M_AXI_BUNDLE4_ARUSER_WIDTH - 1:0] m_axi_bundle4_ARUSER;
input   m_axi_bundle4_RVALID;
output   m_axi_bundle4_RREADY;
input  [C_M_AXI_BUNDLE4_DATA_WIDTH - 1:0] m_axi_bundle4_RDATA;
input   m_axi_bundle4_RLAST;
input  [C_M_AXI_BUNDLE4_ID_WIDTH - 1:0] m_axi_bundle4_RID;
input  [C_M_AXI_BUNDLE4_RUSER_WIDTH - 1:0] m_axi_bundle4_RUSER;
input  [1:0] m_axi_bundle4_RRESP;
input   m_axi_bundle4_BVALID;
output   m_axi_bundle4_BREADY;
input  [1:0] m_axi_bundle4_BRESP;
input  [C_M_AXI_BUNDLE4_ID_WIDTH - 1:0] m_axi_bundle4_BID;
input  [C_M_AXI_BUNDLE4_BUSER_WIDTH - 1:0] m_axi_bundle4_BUSER;
output   m_axi_bundle5_AWVALID;
input   m_axi_bundle5_AWREADY;
output  [C_M_AXI_BUNDLE5_ADDR_WIDTH - 1:0] m_axi_bundle5_AWADDR;
output  [C_M_AXI_BUNDLE5_ID_WIDTH - 1:0] m_axi_bundle5_AWID;
output  [7:0] m_axi_bundle5_AWLEN;
output  [2:0] m_axi_bundle5_AWSIZE;
output  [1:0] m_axi_bundle5_AWBURST;
output  [1:0] m_axi_bundle5_AWLOCK;
output  [3:0] m_axi_bundle5_AWCACHE;
output  [2:0] m_axi_bundle5_AWPROT;
output  [3:0] m_axi_bundle5_AWQOS;
output  [3:0] m_axi_bundle5_AWREGION;
output  [C_M_AXI_BUNDLE5_AWUSER_WIDTH - 1:0] m_axi_bundle5_AWUSER;
output   m_axi_bundle5_WVALID;
input   m_axi_bundle5_WREADY;
output  [C_M_AXI_BUNDLE5_DATA_WIDTH - 1:0] m_axi_bundle5_WDATA;
output  [C_M_AXI_BUNDLE5_WSTRB_WIDTH - 1:0] m_axi_bundle5_WSTRB;
output   m_axi_bundle5_WLAST;
output  [C_M_AXI_BUNDLE5_ID_WIDTH - 1:0] m_axi_bundle5_WID;
output  [C_M_AXI_BUNDLE5_WUSER_WIDTH - 1:0] m_axi_bundle5_WUSER;
output   m_axi_bundle5_ARVALID;
input   m_axi_bundle5_ARREADY;
output  [C_M_AXI_BUNDLE5_ADDR_WIDTH - 1:0] m_axi_bundle5_ARADDR;
output  [C_M_AXI_BUNDLE5_ID_WIDTH - 1:0] m_axi_bundle5_ARID;
output  [7:0] m_axi_bundle5_ARLEN;
output  [2:0] m_axi_bundle5_ARSIZE;
output  [1:0] m_axi_bundle5_ARBURST;
output  [1:0] m_axi_bundle5_ARLOCK;
output  [3:0] m_axi_bundle5_ARCACHE;
output  [2:0] m_axi_bundle5_ARPROT;
output  [3:0] m_axi_bundle5_ARQOS;
output  [3:0] m_axi_bundle5_ARREGION;
output  [C_M_AXI_BUNDLE5_ARUSER_WIDTH - 1:0] m_axi_bundle5_ARUSER;
input   m_axi_bundle5_RVALID;
output   m_axi_bundle5_RREADY;
input  [C_M_AXI_BUNDLE5_DATA_WIDTH - 1:0] m_axi_bundle5_RDATA;
input   m_axi_bundle5_RLAST;
input  [C_M_AXI_BUNDLE5_ID_WIDTH - 1:0] m_axi_bundle5_RID;
input  [C_M_AXI_BUNDLE5_RUSER_WIDTH - 1:0] m_axi_bundle5_RUSER;
input  [1:0] m_axi_bundle5_RRESP;
input   m_axi_bundle5_BVALID;
output   m_axi_bundle5_BREADY;
input  [1:0] m_axi_bundle5_BRESP;
input  [C_M_AXI_BUNDLE5_ID_WIDTH - 1:0] m_axi_bundle5_BID;
input  [C_M_AXI_BUNDLE5_BUSER_WIDTH - 1:0] m_axi_bundle5_BUSER;
output   m_axi_bundle6_AWVALID;
input   m_axi_bundle6_AWREADY;
output  [C_M_AXI_BUNDLE6_ADDR_WIDTH - 1:0] m_axi_bundle6_AWADDR;
output  [C_M_AXI_BUNDLE6_ID_WIDTH - 1:0] m_axi_bundle6_AWID;
output  [7:0] m_axi_bundle6_AWLEN;
output  [2:0] m_axi_bundle6_AWSIZE;
output  [1:0] m_axi_bundle6_AWBURST;
output  [1:0] m_axi_bundle6_AWLOCK;
output  [3:0] m_axi_bundle6_AWCACHE;
output  [2:0] m_axi_bundle6_AWPROT;
output  [3:0] m_axi_bundle6_AWQOS;
output  [3:0] m_axi_bundle6_AWREGION;
output  [C_M_AXI_BUNDLE6_AWUSER_WIDTH - 1:0] m_axi_bundle6_AWUSER;
output   m_axi_bundle6_WVALID;
input   m_axi_bundle6_WREADY;
output  [C_M_AXI_BUNDLE6_DATA_WIDTH - 1:0] m_axi_bundle6_WDATA;
output  [C_M_AXI_BUNDLE6_WSTRB_WIDTH - 1:0] m_axi_bundle6_WSTRB;
output   m_axi_bundle6_WLAST;
output  [C_M_AXI_BUNDLE6_ID_WIDTH - 1:0] m_axi_bundle6_WID;
output  [C_M_AXI_BUNDLE6_WUSER_WIDTH - 1:0] m_axi_bundle6_WUSER;
output   m_axi_bundle6_ARVALID;
input   m_axi_bundle6_ARREADY;
output  [C_M_AXI_BUNDLE6_ADDR_WIDTH - 1:0] m_axi_bundle6_ARADDR;
output  [C_M_AXI_BUNDLE6_ID_WIDTH - 1:0] m_axi_bundle6_ARID;
output  [7:0] m_axi_bundle6_ARLEN;
output  [2:0] m_axi_bundle6_ARSIZE;
output  [1:0] m_axi_bundle6_ARBURST;
output  [1:0] m_axi_bundle6_ARLOCK;
output  [3:0] m_axi_bundle6_ARCACHE;
output  [2:0] m_axi_bundle6_ARPROT;
output  [3:0] m_axi_bundle6_ARQOS;
output  [3:0] m_axi_bundle6_ARREGION;
output  [C_M_AXI_BUNDLE6_ARUSER_WIDTH - 1:0] m_axi_bundle6_ARUSER;
input   m_axi_bundle6_RVALID;
output   m_axi_bundle6_RREADY;
input  [C_M_AXI_BUNDLE6_DATA_WIDTH - 1:0] m_axi_bundle6_RDATA;
input   m_axi_bundle6_RLAST;
input  [C_M_AXI_BUNDLE6_ID_WIDTH - 1:0] m_axi_bundle6_RID;
input  [C_M_AXI_BUNDLE6_RUSER_WIDTH - 1:0] m_axi_bundle6_RUSER;
input  [1:0] m_axi_bundle6_RRESP;
input   m_axi_bundle6_BVALID;
output   m_axi_bundle6_BREADY;
input  [1:0] m_axi_bundle6_BRESP;
input  [C_M_AXI_BUNDLE6_ID_WIDTH - 1:0] m_axi_bundle6_BID;
input  [C_M_AXI_BUNDLE6_BUSER_WIDTH - 1:0] m_axi_bundle6_BUSER;
input  [31:0] input_length;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [63:0] input_real;
wire   [63:0] input_img;
wire   [63:0] kernel_real;
wire   [63:0] kernel_img;
wire   [63:0] output_mag;
wire   [63:0] output_theta;
wire    bundle1_AWREADY;
wire    bundle1_WREADY;
wire    bundle1_ARREADY;
wire    bundle1_RVALID;
wire   [31:0] bundle1_RDATA;
wire    bundle1_RLAST;
wire   [0:0] bundle1_RID;
wire   [8:0] bundle1_RFIFONUM;
wire   [0:0] bundle1_RUSER;
wire   [1:0] bundle1_RRESP;
wire    bundle1_BVALID;
wire    bundle2_AWREADY;
wire    bundle2_WREADY;
wire    bundle2_ARREADY;
wire    bundle2_RVALID;
wire   [31:0] bundle2_RDATA;
wire    bundle2_RLAST;
wire   [0:0] bundle2_RID;
wire   [8:0] bundle2_RFIFONUM;
wire   [0:0] bundle2_RUSER;
wire   [1:0] bundle2_RRESP;
wire    bundle2_BVALID;
wire    bundle3_AWREADY;
wire    bundle3_WREADY;
wire    bundle3_ARREADY;
wire    bundle3_RVALID;
wire   [31:0] bundle3_RDATA;
wire    bundle3_RLAST;
wire   [0:0] bundle3_RID;
wire   [8:0] bundle3_RFIFONUM;
wire   [0:0] bundle3_RUSER;
wire   [1:0] bundle3_RRESP;
wire    bundle3_BVALID;
wire    bundle4_AWREADY;
wire    bundle4_WREADY;
wire    bundle4_ARREADY;
wire    bundle4_RVALID;
wire   [31:0] bundle4_RDATA;
wire    bundle4_RLAST;
wire   [0:0] bundle4_RID;
wire   [8:0] bundle4_RFIFONUM;
wire   [0:0] bundle4_RUSER;
wire   [1:0] bundle4_RRESP;
wire    bundle4_BVALID;
wire    bundle5_AWREADY;
wire    bundle5_WREADY;
wire    bundle5_ARREADY;
wire    bundle5_RVALID;
wire   [31:0] bundle5_RDATA;
wire   [8:0] bundle5_RFIFONUM;
wire    bundle5_BVALID;
wire   [1:0] bundle5_BRESP;
wire   [0:0] bundle5_BID;
wire   [0:0] bundle5_BUSER;
wire    bundle6_AWREADY;
wire    bundle6_WREADY;
wire    bundle6_ARREADY;
wire    bundle6_RVALID;
wire   [31:0] bundle6_RDATA;
wire   [8:0] bundle6_RFIFONUM;
wire    bundle6_BVALID;
wire   [1:0] bundle6_BRESP;
wire   [0:0] bundle6_BID;
wire   [0:0] bundle6_BUSER;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_output_mag_c_din;
wire    entry_proc_U0_output_mag_c_write;
wire   [63:0] entry_proc_U0_output_theta_c_din;
wire    entry_proc_U0_output_theta_c_write;
wire    top_complex_fir_U0_ap_start;
wire    top_complex_fir_U0_ap_done;
wire    top_complex_fir_U0_ap_continue;
wire    top_complex_fir_U0_ap_idle;
wire    top_complex_fir_U0_ap_ready;
wire    top_complex_fir_U0_m_axi_bundle1_AWVALID;
wire   [63:0] top_complex_fir_U0_m_axi_bundle1_AWADDR;
wire   [0:0] top_complex_fir_U0_m_axi_bundle1_AWID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle1_AWLEN;
wire   [2:0] top_complex_fir_U0_m_axi_bundle1_AWSIZE;
wire   [1:0] top_complex_fir_U0_m_axi_bundle1_AWBURST;
wire   [1:0] top_complex_fir_U0_m_axi_bundle1_AWLOCK;
wire   [3:0] top_complex_fir_U0_m_axi_bundle1_AWCACHE;
wire   [2:0] top_complex_fir_U0_m_axi_bundle1_AWPROT;
wire   [3:0] top_complex_fir_U0_m_axi_bundle1_AWQOS;
wire   [3:0] top_complex_fir_U0_m_axi_bundle1_AWREGION;
wire   [0:0] top_complex_fir_U0_m_axi_bundle1_AWUSER;
wire    top_complex_fir_U0_m_axi_bundle1_WVALID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle1_WDATA;
wire   [3:0] top_complex_fir_U0_m_axi_bundle1_WSTRB;
wire    top_complex_fir_U0_m_axi_bundle1_WLAST;
wire   [0:0] top_complex_fir_U0_m_axi_bundle1_WID;
wire   [0:0] top_complex_fir_U0_m_axi_bundle1_WUSER;
wire    top_complex_fir_U0_m_axi_bundle1_ARVALID;
wire   [63:0] top_complex_fir_U0_m_axi_bundle1_ARADDR;
wire   [0:0] top_complex_fir_U0_m_axi_bundle1_ARID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle1_ARLEN;
wire   [2:0] top_complex_fir_U0_m_axi_bundle1_ARSIZE;
wire   [1:0] top_complex_fir_U0_m_axi_bundle1_ARBURST;
wire   [1:0] top_complex_fir_U0_m_axi_bundle1_ARLOCK;
wire   [3:0] top_complex_fir_U0_m_axi_bundle1_ARCACHE;
wire   [2:0] top_complex_fir_U0_m_axi_bundle1_ARPROT;
wire   [3:0] top_complex_fir_U0_m_axi_bundle1_ARQOS;
wire   [3:0] top_complex_fir_U0_m_axi_bundle1_ARREGION;
wire   [0:0] top_complex_fir_U0_m_axi_bundle1_ARUSER;
wire    top_complex_fir_U0_m_axi_bundle1_RREADY;
wire    top_complex_fir_U0_m_axi_bundle1_BREADY;
wire    top_complex_fir_U0_m_axi_bundle2_AWVALID;
wire   [63:0] top_complex_fir_U0_m_axi_bundle2_AWADDR;
wire   [0:0] top_complex_fir_U0_m_axi_bundle2_AWID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle2_AWLEN;
wire   [2:0] top_complex_fir_U0_m_axi_bundle2_AWSIZE;
wire   [1:0] top_complex_fir_U0_m_axi_bundle2_AWBURST;
wire   [1:0] top_complex_fir_U0_m_axi_bundle2_AWLOCK;
wire   [3:0] top_complex_fir_U0_m_axi_bundle2_AWCACHE;
wire   [2:0] top_complex_fir_U0_m_axi_bundle2_AWPROT;
wire   [3:0] top_complex_fir_U0_m_axi_bundle2_AWQOS;
wire   [3:0] top_complex_fir_U0_m_axi_bundle2_AWREGION;
wire   [0:0] top_complex_fir_U0_m_axi_bundle2_AWUSER;
wire    top_complex_fir_U0_m_axi_bundle2_WVALID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle2_WDATA;
wire   [3:0] top_complex_fir_U0_m_axi_bundle2_WSTRB;
wire    top_complex_fir_U0_m_axi_bundle2_WLAST;
wire   [0:0] top_complex_fir_U0_m_axi_bundle2_WID;
wire   [0:0] top_complex_fir_U0_m_axi_bundle2_WUSER;
wire    top_complex_fir_U0_m_axi_bundle2_ARVALID;
wire   [63:0] top_complex_fir_U0_m_axi_bundle2_ARADDR;
wire   [0:0] top_complex_fir_U0_m_axi_bundle2_ARID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle2_ARLEN;
wire   [2:0] top_complex_fir_U0_m_axi_bundle2_ARSIZE;
wire   [1:0] top_complex_fir_U0_m_axi_bundle2_ARBURST;
wire   [1:0] top_complex_fir_U0_m_axi_bundle2_ARLOCK;
wire   [3:0] top_complex_fir_U0_m_axi_bundle2_ARCACHE;
wire   [2:0] top_complex_fir_U0_m_axi_bundle2_ARPROT;
wire   [3:0] top_complex_fir_U0_m_axi_bundle2_ARQOS;
wire   [3:0] top_complex_fir_U0_m_axi_bundle2_ARREGION;
wire   [0:0] top_complex_fir_U0_m_axi_bundle2_ARUSER;
wire    top_complex_fir_U0_m_axi_bundle2_RREADY;
wire    top_complex_fir_U0_m_axi_bundle2_BREADY;
wire    top_complex_fir_U0_m_axi_bundle3_AWVALID;
wire   [63:0] top_complex_fir_U0_m_axi_bundle3_AWADDR;
wire   [0:0] top_complex_fir_U0_m_axi_bundle3_AWID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle3_AWLEN;
wire   [2:0] top_complex_fir_U0_m_axi_bundle3_AWSIZE;
wire   [1:0] top_complex_fir_U0_m_axi_bundle3_AWBURST;
wire   [1:0] top_complex_fir_U0_m_axi_bundle3_AWLOCK;
wire   [3:0] top_complex_fir_U0_m_axi_bundle3_AWCACHE;
wire   [2:0] top_complex_fir_U0_m_axi_bundle3_AWPROT;
wire   [3:0] top_complex_fir_U0_m_axi_bundle3_AWQOS;
wire   [3:0] top_complex_fir_U0_m_axi_bundle3_AWREGION;
wire   [0:0] top_complex_fir_U0_m_axi_bundle3_AWUSER;
wire    top_complex_fir_U0_m_axi_bundle3_WVALID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle3_WDATA;
wire   [3:0] top_complex_fir_U0_m_axi_bundle3_WSTRB;
wire    top_complex_fir_U0_m_axi_bundle3_WLAST;
wire   [0:0] top_complex_fir_U0_m_axi_bundle3_WID;
wire   [0:0] top_complex_fir_U0_m_axi_bundle3_WUSER;
wire    top_complex_fir_U0_m_axi_bundle3_ARVALID;
wire   [63:0] top_complex_fir_U0_m_axi_bundle3_ARADDR;
wire   [0:0] top_complex_fir_U0_m_axi_bundle3_ARID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle3_ARLEN;
wire   [2:0] top_complex_fir_U0_m_axi_bundle3_ARSIZE;
wire   [1:0] top_complex_fir_U0_m_axi_bundle3_ARBURST;
wire   [1:0] top_complex_fir_U0_m_axi_bundle3_ARLOCK;
wire   [3:0] top_complex_fir_U0_m_axi_bundle3_ARCACHE;
wire   [2:0] top_complex_fir_U0_m_axi_bundle3_ARPROT;
wire   [3:0] top_complex_fir_U0_m_axi_bundle3_ARQOS;
wire   [3:0] top_complex_fir_U0_m_axi_bundle3_ARREGION;
wire   [0:0] top_complex_fir_U0_m_axi_bundle3_ARUSER;
wire    top_complex_fir_U0_m_axi_bundle3_RREADY;
wire    top_complex_fir_U0_m_axi_bundle3_BREADY;
wire    top_complex_fir_U0_m_axi_bundle4_AWVALID;
wire   [63:0] top_complex_fir_U0_m_axi_bundle4_AWADDR;
wire   [0:0] top_complex_fir_U0_m_axi_bundle4_AWID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle4_AWLEN;
wire   [2:0] top_complex_fir_U0_m_axi_bundle4_AWSIZE;
wire   [1:0] top_complex_fir_U0_m_axi_bundle4_AWBURST;
wire   [1:0] top_complex_fir_U0_m_axi_bundle4_AWLOCK;
wire   [3:0] top_complex_fir_U0_m_axi_bundle4_AWCACHE;
wire   [2:0] top_complex_fir_U0_m_axi_bundle4_AWPROT;
wire   [3:0] top_complex_fir_U0_m_axi_bundle4_AWQOS;
wire   [3:0] top_complex_fir_U0_m_axi_bundle4_AWREGION;
wire   [0:0] top_complex_fir_U0_m_axi_bundle4_AWUSER;
wire    top_complex_fir_U0_m_axi_bundle4_WVALID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle4_WDATA;
wire   [3:0] top_complex_fir_U0_m_axi_bundle4_WSTRB;
wire    top_complex_fir_U0_m_axi_bundle4_WLAST;
wire   [0:0] top_complex_fir_U0_m_axi_bundle4_WID;
wire   [0:0] top_complex_fir_U0_m_axi_bundle4_WUSER;
wire    top_complex_fir_U0_m_axi_bundle4_ARVALID;
wire   [63:0] top_complex_fir_U0_m_axi_bundle4_ARADDR;
wire   [0:0] top_complex_fir_U0_m_axi_bundle4_ARID;
wire   [31:0] top_complex_fir_U0_m_axi_bundle4_ARLEN;
wire   [2:0] top_complex_fir_U0_m_axi_bundle4_ARSIZE;
wire   [1:0] top_complex_fir_U0_m_axi_bundle4_ARBURST;
wire   [1:0] top_complex_fir_U0_m_axi_bundle4_ARLOCK;
wire   [3:0] top_complex_fir_U0_m_axi_bundle4_ARCACHE;
wire   [2:0] top_complex_fir_U0_m_axi_bundle4_ARPROT;
wire   [3:0] top_complex_fir_U0_m_axi_bundle4_ARQOS;
wire   [3:0] top_complex_fir_U0_m_axi_bundle4_ARREGION;
wire   [0:0] top_complex_fir_U0_m_axi_bundle4_ARUSER;
wire    top_complex_fir_U0_m_axi_bundle4_RREADY;
wire    top_complex_fir_U0_m_axi_bundle4_BREADY;
wire   [31:0] top_complex_fir_U0_img_stream2_din;
wire    top_complex_fir_U0_img_stream2_write;
wire   [31:0] top_complex_fir_U0_real_stream3_din;
wire    top_complex_fir_U0_real_stream3_write;
wire   [31:0] top_complex_fir_U0_input_length_c_din;
wire    top_complex_fir_U0_input_length_c_write;
wire    top_cordic_U0_ap_start;
wire    top_cordic_U0_ap_done;
wire    top_cordic_U0_ap_continue;
wire    top_cordic_U0_ap_idle;
wire    top_cordic_U0_ap_ready;
wire    top_cordic_U0_img_stream2_read;
wire    top_cordic_U0_real_stream3_read;
wire    top_cordic_U0_m_axi_bundle5_AWVALID;
wire   [63:0] top_cordic_U0_m_axi_bundle5_AWADDR;
wire   [0:0] top_cordic_U0_m_axi_bundle5_AWID;
wire   [31:0] top_cordic_U0_m_axi_bundle5_AWLEN;
wire   [2:0] top_cordic_U0_m_axi_bundle5_AWSIZE;
wire   [1:0] top_cordic_U0_m_axi_bundle5_AWBURST;
wire   [1:0] top_cordic_U0_m_axi_bundle5_AWLOCK;
wire   [3:0] top_cordic_U0_m_axi_bundle5_AWCACHE;
wire   [2:0] top_cordic_U0_m_axi_bundle5_AWPROT;
wire   [3:0] top_cordic_U0_m_axi_bundle5_AWQOS;
wire   [3:0] top_cordic_U0_m_axi_bundle5_AWREGION;
wire   [0:0] top_cordic_U0_m_axi_bundle5_AWUSER;
wire    top_cordic_U0_m_axi_bundle5_WVALID;
wire   [31:0] top_cordic_U0_m_axi_bundle5_WDATA;
wire   [3:0] top_cordic_U0_m_axi_bundle5_WSTRB;
wire    top_cordic_U0_m_axi_bundle5_WLAST;
wire   [0:0] top_cordic_U0_m_axi_bundle5_WID;
wire   [0:0] top_cordic_U0_m_axi_bundle5_WUSER;
wire    top_cordic_U0_m_axi_bundle5_ARVALID;
wire   [63:0] top_cordic_U0_m_axi_bundle5_ARADDR;
wire   [0:0] top_cordic_U0_m_axi_bundle5_ARID;
wire   [31:0] top_cordic_U0_m_axi_bundle5_ARLEN;
wire   [2:0] top_cordic_U0_m_axi_bundle5_ARSIZE;
wire   [1:0] top_cordic_U0_m_axi_bundle5_ARBURST;
wire   [1:0] top_cordic_U0_m_axi_bundle5_ARLOCK;
wire   [3:0] top_cordic_U0_m_axi_bundle5_ARCACHE;
wire   [2:0] top_cordic_U0_m_axi_bundle5_ARPROT;
wire   [3:0] top_cordic_U0_m_axi_bundle5_ARQOS;
wire   [3:0] top_cordic_U0_m_axi_bundle5_ARREGION;
wire   [0:0] top_cordic_U0_m_axi_bundle5_ARUSER;
wire    top_cordic_U0_m_axi_bundle5_RREADY;
wire    top_cordic_U0_m_axi_bundle5_BREADY;
wire    top_cordic_U0_output_mag_read;
wire    top_cordic_U0_m_axi_bundle6_AWVALID;
wire   [63:0] top_cordic_U0_m_axi_bundle6_AWADDR;
wire   [0:0] top_cordic_U0_m_axi_bundle6_AWID;
wire   [31:0] top_cordic_U0_m_axi_bundle6_AWLEN;
wire   [2:0] top_cordic_U0_m_axi_bundle6_AWSIZE;
wire   [1:0] top_cordic_U0_m_axi_bundle6_AWBURST;
wire   [1:0] top_cordic_U0_m_axi_bundle6_AWLOCK;
wire   [3:0] top_cordic_U0_m_axi_bundle6_AWCACHE;
wire   [2:0] top_cordic_U0_m_axi_bundle6_AWPROT;
wire   [3:0] top_cordic_U0_m_axi_bundle6_AWQOS;
wire   [3:0] top_cordic_U0_m_axi_bundle6_AWREGION;
wire   [0:0] top_cordic_U0_m_axi_bundle6_AWUSER;
wire    top_cordic_U0_m_axi_bundle6_WVALID;
wire   [31:0] top_cordic_U0_m_axi_bundle6_WDATA;
wire   [3:0] top_cordic_U0_m_axi_bundle6_WSTRB;
wire    top_cordic_U0_m_axi_bundle6_WLAST;
wire   [0:0] top_cordic_U0_m_axi_bundle6_WID;
wire   [0:0] top_cordic_U0_m_axi_bundle6_WUSER;
wire    top_cordic_U0_m_axi_bundle6_ARVALID;
wire   [63:0] top_cordic_U0_m_axi_bundle6_ARADDR;
wire   [0:0] top_cordic_U0_m_axi_bundle6_ARID;
wire   [31:0] top_cordic_U0_m_axi_bundle6_ARLEN;
wire   [2:0] top_cordic_U0_m_axi_bundle6_ARSIZE;
wire   [1:0] top_cordic_U0_m_axi_bundle6_ARBURST;
wire   [1:0] top_cordic_U0_m_axi_bundle6_ARLOCK;
wire   [3:0] top_cordic_U0_m_axi_bundle6_ARCACHE;
wire   [2:0] top_cordic_U0_m_axi_bundle6_ARPROT;
wire   [3:0] top_cordic_U0_m_axi_bundle6_ARQOS;
wire   [3:0] top_cordic_U0_m_axi_bundle6_ARREGION;
wire   [0:0] top_cordic_U0_m_axi_bundle6_ARUSER;
wire    top_cordic_U0_m_axi_bundle6_RREADY;
wire    top_cordic_U0_m_axi_bundle6_BREADY;
wire    top_cordic_U0_output_theta_read;
wire    top_cordic_U0_input_length_read;
wire    output_mag_c_full_n;
wire   [63:0] output_mag_c_dout;
wire   [2:0] output_mag_c_num_data_valid;
wire   [2:0] output_mag_c_fifo_cap;
wire    output_mag_c_empty_n;
wire    output_theta_c_full_n;
wire   [63:0] output_theta_c_dout;
wire   [2:0] output_theta_c_num_data_valid;
wire   [2:0] output_theta_c_fifo_cap;
wire    output_theta_c_empty_n;
wire    img_stream_full_n;
wire   [31:0] img_stream_dout;
wire   [1:0] img_stream_num_data_valid;
wire   [1:0] img_stream_fifo_cap;
wire    img_stream_empty_n;
wire    real_stream_full_n;
wire   [31:0] real_stream_dout;
wire   [1:0] real_stream_num_data_valid;
wire   [1:0] real_stream_fifo_cap;
wire    real_stream_empty_n;
wire    input_length_c_full_n;
wire   [31:0] input_length_c_dout;
wire   [1:0] input_length_c_num_data_valid;
wire   [1:0] input_length_c_fifo_cap;
wire    input_length_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_top_complex_fir_U0_ap_ready;
wire    ap_sync_top_complex_fir_U0_ap_ready;
wire   [0:0] start_for_top_cordic_U0_din;
wire    start_for_top_cordic_U0_full_n;
wire   [0:0] start_for_top_cordic_U0_dout;
wire    start_for_top_cordic_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_top_complex_fir_U0_ap_ready = 1'b0;
end

top_fpga417_bundle8_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_BUNDLE8_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_BUNDLE8_DATA_WIDTH ))
bundle8_s_axi_U(
    .AWVALID(s_axi_bundle8_AWVALID),
    .AWREADY(s_axi_bundle8_AWREADY),
    .AWADDR(s_axi_bundle8_AWADDR),
    .WVALID(s_axi_bundle8_WVALID),
    .WREADY(s_axi_bundle8_WREADY),
    .WDATA(s_axi_bundle8_WDATA),
    .WSTRB(s_axi_bundle8_WSTRB),
    .ARVALID(s_axi_bundle8_ARVALID),
    .ARREADY(s_axi_bundle8_ARREADY),
    .ARADDR(s_axi_bundle8_ARADDR),
    .RVALID(s_axi_bundle8_RVALID),
    .RREADY(s_axi_bundle8_RREADY),
    .RDATA(s_axi_bundle8_RDATA),
    .RRESP(s_axi_bundle8_RRESP),
    .BVALID(s_axi_bundle8_BVALID),
    .BREADY(s_axi_bundle8_BREADY),
    .BRESP(s_axi_bundle8_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

top_fpga417_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_real(input_real),
    .input_img(input_img),
    .kernel_real(kernel_real),
    .kernel_img(kernel_img),
    .output_mag(output_mag),
    .output_theta(output_theta)
);

top_fpga417_bundle1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUNDLE1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUNDLE1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUNDLE1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUNDLE1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUNDLE1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUNDLE1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUNDLE1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUNDLE1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUNDLE1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUNDLE1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUNDLE1_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
bundle1_m_axi_U(
    .AWVALID(m_axi_bundle1_AWVALID),
    .AWREADY(m_axi_bundle1_AWREADY),
    .AWADDR(m_axi_bundle1_AWADDR),
    .AWID(m_axi_bundle1_AWID),
    .AWLEN(m_axi_bundle1_AWLEN),
    .AWSIZE(m_axi_bundle1_AWSIZE),
    .AWBURST(m_axi_bundle1_AWBURST),
    .AWLOCK(m_axi_bundle1_AWLOCK),
    .AWCACHE(m_axi_bundle1_AWCACHE),
    .AWPROT(m_axi_bundle1_AWPROT),
    .AWQOS(m_axi_bundle1_AWQOS),
    .AWREGION(m_axi_bundle1_AWREGION),
    .AWUSER(m_axi_bundle1_AWUSER),
    .WVALID(m_axi_bundle1_WVALID),
    .WREADY(m_axi_bundle1_WREADY),
    .WDATA(m_axi_bundle1_WDATA),
    .WSTRB(m_axi_bundle1_WSTRB),
    .WLAST(m_axi_bundle1_WLAST),
    .WID(m_axi_bundle1_WID),
    .WUSER(m_axi_bundle1_WUSER),
    .ARVALID(m_axi_bundle1_ARVALID),
    .ARREADY(m_axi_bundle1_ARREADY),
    .ARADDR(m_axi_bundle1_ARADDR),
    .ARID(m_axi_bundle1_ARID),
    .ARLEN(m_axi_bundle1_ARLEN),
    .ARSIZE(m_axi_bundle1_ARSIZE),
    .ARBURST(m_axi_bundle1_ARBURST),
    .ARLOCK(m_axi_bundle1_ARLOCK),
    .ARCACHE(m_axi_bundle1_ARCACHE),
    .ARPROT(m_axi_bundle1_ARPROT),
    .ARQOS(m_axi_bundle1_ARQOS),
    .ARREGION(m_axi_bundle1_ARREGION),
    .ARUSER(m_axi_bundle1_ARUSER),
    .RVALID(m_axi_bundle1_RVALID),
    .RREADY(m_axi_bundle1_RREADY),
    .RDATA(m_axi_bundle1_RDATA),
    .RLAST(m_axi_bundle1_RLAST),
    .RID(m_axi_bundle1_RID),
    .RUSER(m_axi_bundle1_RUSER),
    .RRESP(m_axi_bundle1_RRESP),
    .BVALID(m_axi_bundle1_BVALID),
    .BREADY(m_axi_bundle1_BREADY),
    .BRESP(m_axi_bundle1_BRESP),
    .BID(m_axi_bundle1_BID),
    .BUSER(m_axi_bundle1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(top_complex_fir_U0_m_axi_bundle1_ARVALID),
    .I_ARREADY(bundle1_ARREADY),
    .I_ARADDR(top_complex_fir_U0_m_axi_bundle1_ARADDR),
    .I_ARLEN(top_complex_fir_U0_m_axi_bundle1_ARLEN),
    .I_RVALID(bundle1_RVALID),
    .I_RREADY(top_complex_fir_U0_m_axi_bundle1_RREADY),
    .I_RDATA(bundle1_RDATA),
    .I_RFIFONUM(bundle1_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(bundle1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(bundle1_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(bundle1_BVALID),
    .I_BREADY(1'b0)
);

top_fpga417_bundle2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUNDLE2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUNDLE2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUNDLE2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUNDLE2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUNDLE2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUNDLE2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUNDLE2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUNDLE2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUNDLE2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUNDLE2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUNDLE2_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
bundle2_m_axi_U(
    .AWVALID(m_axi_bundle2_AWVALID),
    .AWREADY(m_axi_bundle2_AWREADY),
    .AWADDR(m_axi_bundle2_AWADDR),
    .AWID(m_axi_bundle2_AWID),
    .AWLEN(m_axi_bundle2_AWLEN),
    .AWSIZE(m_axi_bundle2_AWSIZE),
    .AWBURST(m_axi_bundle2_AWBURST),
    .AWLOCK(m_axi_bundle2_AWLOCK),
    .AWCACHE(m_axi_bundle2_AWCACHE),
    .AWPROT(m_axi_bundle2_AWPROT),
    .AWQOS(m_axi_bundle2_AWQOS),
    .AWREGION(m_axi_bundle2_AWREGION),
    .AWUSER(m_axi_bundle2_AWUSER),
    .WVALID(m_axi_bundle2_WVALID),
    .WREADY(m_axi_bundle2_WREADY),
    .WDATA(m_axi_bundle2_WDATA),
    .WSTRB(m_axi_bundle2_WSTRB),
    .WLAST(m_axi_bundle2_WLAST),
    .WID(m_axi_bundle2_WID),
    .WUSER(m_axi_bundle2_WUSER),
    .ARVALID(m_axi_bundle2_ARVALID),
    .ARREADY(m_axi_bundle2_ARREADY),
    .ARADDR(m_axi_bundle2_ARADDR),
    .ARID(m_axi_bundle2_ARID),
    .ARLEN(m_axi_bundle2_ARLEN),
    .ARSIZE(m_axi_bundle2_ARSIZE),
    .ARBURST(m_axi_bundle2_ARBURST),
    .ARLOCK(m_axi_bundle2_ARLOCK),
    .ARCACHE(m_axi_bundle2_ARCACHE),
    .ARPROT(m_axi_bundle2_ARPROT),
    .ARQOS(m_axi_bundle2_ARQOS),
    .ARREGION(m_axi_bundle2_ARREGION),
    .ARUSER(m_axi_bundle2_ARUSER),
    .RVALID(m_axi_bundle2_RVALID),
    .RREADY(m_axi_bundle2_RREADY),
    .RDATA(m_axi_bundle2_RDATA),
    .RLAST(m_axi_bundle2_RLAST),
    .RID(m_axi_bundle2_RID),
    .RUSER(m_axi_bundle2_RUSER),
    .RRESP(m_axi_bundle2_RRESP),
    .BVALID(m_axi_bundle2_BVALID),
    .BREADY(m_axi_bundle2_BREADY),
    .BRESP(m_axi_bundle2_BRESP),
    .BID(m_axi_bundle2_BID),
    .BUSER(m_axi_bundle2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(top_complex_fir_U0_m_axi_bundle2_ARVALID),
    .I_ARREADY(bundle2_ARREADY),
    .I_ARADDR(top_complex_fir_U0_m_axi_bundle2_ARADDR),
    .I_ARLEN(top_complex_fir_U0_m_axi_bundle2_ARLEN),
    .I_RVALID(bundle2_RVALID),
    .I_RREADY(top_complex_fir_U0_m_axi_bundle2_RREADY),
    .I_RDATA(bundle2_RDATA),
    .I_RFIFONUM(bundle2_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(bundle2_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(bundle2_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(bundle2_BVALID),
    .I_BREADY(1'b0)
);

top_fpga417_bundle3_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUNDLE3_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUNDLE3_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUNDLE3_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUNDLE3_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUNDLE3_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUNDLE3_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUNDLE3_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUNDLE3_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUNDLE3_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUNDLE3_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUNDLE3_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
bundle3_m_axi_U(
    .AWVALID(m_axi_bundle3_AWVALID),
    .AWREADY(m_axi_bundle3_AWREADY),
    .AWADDR(m_axi_bundle3_AWADDR),
    .AWID(m_axi_bundle3_AWID),
    .AWLEN(m_axi_bundle3_AWLEN),
    .AWSIZE(m_axi_bundle3_AWSIZE),
    .AWBURST(m_axi_bundle3_AWBURST),
    .AWLOCK(m_axi_bundle3_AWLOCK),
    .AWCACHE(m_axi_bundle3_AWCACHE),
    .AWPROT(m_axi_bundle3_AWPROT),
    .AWQOS(m_axi_bundle3_AWQOS),
    .AWREGION(m_axi_bundle3_AWREGION),
    .AWUSER(m_axi_bundle3_AWUSER),
    .WVALID(m_axi_bundle3_WVALID),
    .WREADY(m_axi_bundle3_WREADY),
    .WDATA(m_axi_bundle3_WDATA),
    .WSTRB(m_axi_bundle3_WSTRB),
    .WLAST(m_axi_bundle3_WLAST),
    .WID(m_axi_bundle3_WID),
    .WUSER(m_axi_bundle3_WUSER),
    .ARVALID(m_axi_bundle3_ARVALID),
    .ARREADY(m_axi_bundle3_ARREADY),
    .ARADDR(m_axi_bundle3_ARADDR),
    .ARID(m_axi_bundle3_ARID),
    .ARLEN(m_axi_bundle3_ARLEN),
    .ARSIZE(m_axi_bundle3_ARSIZE),
    .ARBURST(m_axi_bundle3_ARBURST),
    .ARLOCK(m_axi_bundle3_ARLOCK),
    .ARCACHE(m_axi_bundle3_ARCACHE),
    .ARPROT(m_axi_bundle3_ARPROT),
    .ARQOS(m_axi_bundle3_ARQOS),
    .ARREGION(m_axi_bundle3_ARREGION),
    .ARUSER(m_axi_bundle3_ARUSER),
    .RVALID(m_axi_bundle3_RVALID),
    .RREADY(m_axi_bundle3_RREADY),
    .RDATA(m_axi_bundle3_RDATA),
    .RLAST(m_axi_bundle3_RLAST),
    .RID(m_axi_bundle3_RID),
    .RUSER(m_axi_bundle3_RUSER),
    .RRESP(m_axi_bundle3_RRESP),
    .BVALID(m_axi_bundle3_BVALID),
    .BREADY(m_axi_bundle3_BREADY),
    .BRESP(m_axi_bundle3_BRESP),
    .BID(m_axi_bundle3_BID),
    .BUSER(m_axi_bundle3_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(top_complex_fir_U0_m_axi_bundle3_ARVALID),
    .I_ARREADY(bundle3_ARREADY),
    .I_ARADDR(top_complex_fir_U0_m_axi_bundle3_ARADDR),
    .I_ARLEN(top_complex_fir_U0_m_axi_bundle3_ARLEN),
    .I_RVALID(bundle3_RVALID),
    .I_RREADY(top_complex_fir_U0_m_axi_bundle3_RREADY),
    .I_RDATA(bundle3_RDATA),
    .I_RFIFONUM(bundle3_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(bundle3_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(bundle3_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(bundle3_BVALID),
    .I_BREADY(1'b0)
);

top_fpga417_bundle4_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUNDLE4_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUNDLE4_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUNDLE4_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUNDLE4_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUNDLE4_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUNDLE4_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUNDLE4_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUNDLE4_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUNDLE4_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUNDLE4_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUNDLE4_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
bundle4_m_axi_U(
    .AWVALID(m_axi_bundle4_AWVALID),
    .AWREADY(m_axi_bundle4_AWREADY),
    .AWADDR(m_axi_bundle4_AWADDR),
    .AWID(m_axi_bundle4_AWID),
    .AWLEN(m_axi_bundle4_AWLEN),
    .AWSIZE(m_axi_bundle4_AWSIZE),
    .AWBURST(m_axi_bundle4_AWBURST),
    .AWLOCK(m_axi_bundle4_AWLOCK),
    .AWCACHE(m_axi_bundle4_AWCACHE),
    .AWPROT(m_axi_bundle4_AWPROT),
    .AWQOS(m_axi_bundle4_AWQOS),
    .AWREGION(m_axi_bundle4_AWREGION),
    .AWUSER(m_axi_bundle4_AWUSER),
    .WVALID(m_axi_bundle4_WVALID),
    .WREADY(m_axi_bundle4_WREADY),
    .WDATA(m_axi_bundle4_WDATA),
    .WSTRB(m_axi_bundle4_WSTRB),
    .WLAST(m_axi_bundle4_WLAST),
    .WID(m_axi_bundle4_WID),
    .WUSER(m_axi_bundle4_WUSER),
    .ARVALID(m_axi_bundle4_ARVALID),
    .ARREADY(m_axi_bundle4_ARREADY),
    .ARADDR(m_axi_bundle4_ARADDR),
    .ARID(m_axi_bundle4_ARID),
    .ARLEN(m_axi_bundle4_ARLEN),
    .ARSIZE(m_axi_bundle4_ARSIZE),
    .ARBURST(m_axi_bundle4_ARBURST),
    .ARLOCK(m_axi_bundle4_ARLOCK),
    .ARCACHE(m_axi_bundle4_ARCACHE),
    .ARPROT(m_axi_bundle4_ARPROT),
    .ARQOS(m_axi_bundle4_ARQOS),
    .ARREGION(m_axi_bundle4_ARREGION),
    .ARUSER(m_axi_bundle4_ARUSER),
    .RVALID(m_axi_bundle4_RVALID),
    .RREADY(m_axi_bundle4_RREADY),
    .RDATA(m_axi_bundle4_RDATA),
    .RLAST(m_axi_bundle4_RLAST),
    .RID(m_axi_bundle4_RID),
    .RUSER(m_axi_bundle4_RUSER),
    .RRESP(m_axi_bundle4_RRESP),
    .BVALID(m_axi_bundle4_BVALID),
    .BREADY(m_axi_bundle4_BREADY),
    .BRESP(m_axi_bundle4_BRESP),
    .BID(m_axi_bundle4_BID),
    .BUSER(m_axi_bundle4_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(top_complex_fir_U0_m_axi_bundle4_ARVALID),
    .I_ARREADY(bundle4_ARREADY),
    .I_ARADDR(top_complex_fir_U0_m_axi_bundle4_ARADDR),
    .I_ARLEN(top_complex_fir_U0_m_axi_bundle4_ARLEN),
    .I_RVALID(bundle4_RVALID),
    .I_RREADY(top_complex_fir_U0_m_axi_bundle4_RREADY),
    .I_RDATA(bundle4_RDATA),
    .I_RFIFONUM(bundle4_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(bundle4_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(bundle4_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(bundle4_BVALID),
    .I_BREADY(1'b0)
);

top_fpga417_bundle5_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUNDLE5_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUNDLE5_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUNDLE5_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUNDLE5_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUNDLE5_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUNDLE5_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUNDLE5_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUNDLE5_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUNDLE5_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUNDLE5_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUNDLE5_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
bundle5_m_axi_U(
    .AWVALID(m_axi_bundle5_AWVALID),
    .AWREADY(m_axi_bundle5_AWREADY),
    .AWADDR(m_axi_bundle5_AWADDR),
    .AWID(m_axi_bundle5_AWID),
    .AWLEN(m_axi_bundle5_AWLEN),
    .AWSIZE(m_axi_bundle5_AWSIZE),
    .AWBURST(m_axi_bundle5_AWBURST),
    .AWLOCK(m_axi_bundle5_AWLOCK),
    .AWCACHE(m_axi_bundle5_AWCACHE),
    .AWPROT(m_axi_bundle5_AWPROT),
    .AWQOS(m_axi_bundle5_AWQOS),
    .AWREGION(m_axi_bundle5_AWREGION),
    .AWUSER(m_axi_bundle5_AWUSER),
    .WVALID(m_axi_bundle5_WVALID),
    .WREADY(m_axi_bundle5_WREADY),
    .WDATA(m_axi_bundle5_WDATA),
    .WSTRB(m_axi_bundle5_WSTRB),
    .WLAST(m_axi_bundle5_WLAST),
    .WID(m_axi_bundle5_WID),
    .WUSER(m_axi_bundle5_WUSER),
    .ARVALID(m_axi_bundle5_ARVALID),
    .ARREADY(m_axi_bundle5_ARREADY),
    .ARADDR(m_axi_bundle5_ARADDR),
    .ARID(m_axi_bundle5_ARID),
    .ARLEN(m_axi_bundle5_ARLEN),
    .ARSIZE(m_axi_bundle5_ARSIZE),
    .ARBURST(m_axi_bundle5_ARBURST),
    .ARLOCK(m_axi_bundle5_ARLOCK),
    .ARCACHE(m_axi_bundle5_ARCACHE),
    .ARPROT(m_axi_bundle5_ARPROT),
    .ARQOS(m_axi_bundle5_ARQOS),
    .ARREGION(m_axi_bundle5_ARREGION),
    .ARUSER(m_axi_bundle5_ARUSER),
    .RVALID(m_axi_bundle5_RVALID),
    .RREADY(m_axi_bundle5_RREADY),
    .RDATA(m_axi_bundle5_RDATA),
    .RLAST(m_axi_bundle5_RLAST),
    .RID(m_axi_bundle5_RID),
    .RUSER(m_axi_bundle5_RUSER),
    .RRESP(m_axi_bundle5_RRESP),
    .BVALID(m_axi_bundle5_BVALID),
    .BREADY(m_axi_bundle5_BREADY),
    .BRESP(m_axi_bundle5_BRESP),
    .BID(m_axi_bundle5_BID),
    .BUSER(m_axi_bundle5_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(bundle5_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(bundle5_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(bundle5_RDATA),
    .I_RFIFONUM(bundle5_RFIFONUM),
    .I_AWVALID(top_cordic_U0_m_axi_bundle5_AWVALID),
    .I_AWREADY(bundle5_AWREADY),
    .I_AWADDR(top_cordic_U0_m_axi_bundle5_AWADDR),
    .I_AWLEN(top_cordic_U0_m_axi_bundle5_AWLEN),
    .I_WVALID(top_cordic_U0_m_axi_bundle5_WVALID),
    .I_WREADY(bundle5_WREADY),
    .I_WDATA(top_cordic_U0_m_axi_bundle5_WDATA),
    .I_WSTRB(top_cordic_U0_m_axi_bundle5_WSTRB),
    .I_BVALID(bundle5_BVALID),
    .I_BREADY(top_cordic_U0_m_axi_bundle5_BREADY)
);

top_fpga417_bundle6_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUNDLE6_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUNDLE6_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUNDLE6_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUNDLE6_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUNDLE6_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUNDLE6_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUNDLE6_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUNDLE6_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUNDLE6_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUNDLE6_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUNDLE6_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
bundle6_m_axi_U(
    .AWVALID(m_axi_bundle6_AWVALID),
    .AWREADY(m_axi_bundle6_AWREADY),
    .AWADDR(m_axi_bundle6_AWADDR),
    .AWID(m_axi_bundle6_AWID),
    .AWLEN(m_axi_bundle6_AWLEN),
    .AWSIZE(m_axi_bundle6_AWSIZE),
    .AWBURST(m_axi_bundle6_AWBURST),
    .AWLOCK(m_axi_bundle6_AWLOCK),
    .AWCACHE(m_axi_bundle6_AWCACHE),
    .AWPROT(m_axi_bundle6_AWPROT),
    .AWQOS(m_axi_bundle6_AWQOS),
    .AWREGION(m_axi_bundle6_AWREGION),
    .AWUSER(m_axi_bundle6_AWUSER),
    .WVALID(m_axi_bundle6_WVALID),
    .WREADY(m_axi_bundle6_WREADY),
    .WDATA(m_axi_bundle6_WDATA),
    .WSTRB(m_axi_bundle6_WSTRB),
    .WLAST(m_axi_bundle6_WLAST),
    .WID(m_axi_bundle6_WID),
    .WUSER(m_axi_bundle6_WUSER),
    .ARVALID(m_axi_bundle6_ARVALID),
    .ARREADY(m_axi_bundle6_ARREADY),
    .ARADDR(m_axi_bundle6_ARADDR),
    .ARID(m_axi_bundle6_ARID),
    .ARLEN(m_axi_bundle6_ARLEN),
    .ARSIZE(m_axi_bundle6_ARSIZE),
    .ARBURST(m_axi_bundle6_ARBURST),
    .ARLOCK(m_axi_bundle6_ARLOCK),
    .ARCACHE(m_axi_bundle6_ARCACHE),
    .ARPROT(m_axi_bundle6_ARPROT),
    .ARQOS(m_axi_bundle6_ARQOS),
    .ARREGION(m_axi_bundle6_ARREGION),
    .ARUSER(m_axi_bundle6_ARUSER),
    .RVALID(m_axi_bundle6_RVALID),
    .RREADY(m_axi_bundle6_RREADY),
    .RDATA(m_axi_bundle6_RDATA),
    .RLAST(m_axi_bundle6_RLAST),
    .RID(m_axi_bundle6_RID),
    .RUSER(m_axi_bundle6_RUSER),
    .RRESP(m_axi_bundle6_RRESP),
    .BVALID(m_axi_bundle6_BVALID),
    .BREADY(m_axi_bundle6_BREADY),
    .BRESP(m_axi_bundle6_BRESP),
    .BID(m_axi_bundle6_BID),
    .BUSER(m_axi_bundle6_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(bundle6_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(bundle6_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(bundle6_RDATA),
    .I_RFIFONUM(bundle6_RFIFONUM),
    .I_AWVALID(top_cordic_U0_m_axi_bundle6_AWVALID),
    .I_AWREADY(bundle6_AWREADY),
    .I_AWADDR(top_cordic_U0_m_axi_bundle6_AWADDR),
    .I_AWLEN(top_cordic_U0_m_axi_bundle6_AWLEN),
    .I_WVALID(top_cordic_U0_m_axi_bundle6_WVALID),
    .I_WREADY(bundle6_WREADY),
    .I_WDATA(top_cordic_U0_m_axi_bundle6_WDATA),
    .I_WSTRB(top_cordic_U0_m_axi_bundle6_WSTRB),
    .I_BVALID(bundle6_BVALID),
    .I_BREADY(top_cordic_U0_m_axi_bundle6_BREADY)
);

top_fpga417_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_top_cordic_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .output_mag(output_mag),
    .output_mag_c_din(entry_proc_U0_output_mag_c_din),
    .output_mag_c_num_data_valid(output_mag_c_num_data_valid),
    .output_mag_c_fifo_cap(output_mag_c_fifo_cap),
    .output_mag_c_full_n(output_mag_c_full_n),
    .output_mag_c_write(entry_proc_U0_output_mag_c_write),
    .output_theta(output_theta),
    .output_theta_c_din(entry_proc_U0_output_theta_c_din),
    .output_theta_c_num_data_valid(output_theta_c_num_data_valid),
    .output_theta_c_fifo_cap(output_theta_c_fifo_cap),
    .output_theta_c_full_n(output_theta_c_full_n),
    .output_theta_c_write(entry_proc_U0_output_theta_c_write)
);

top_fpga417_top_complex_fir top_complex_fir_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(top_complex_fir_U0_ap_start),
    .ap_done(top_complex_fir_U0_ap_done),
    .ap_continue(top_complex_fir_U0_ap_continue),
    .ap_idle(top_complex_fir_U0_ap_idle),
    .ap_ready(top_complex_fir_U0_ap_ready),
    .m_axi_bundle1_AWVALID(top_complex_fir_U0_m_axi_bundle1_AWVALID),
    .m_axi_bundle1_AWREADY(1'b0),
    .m_axi_bundle1_AWADDR(top_complex_fir_U0_m_axi_bundle1_AWADDR),
    .m_axi_bundle1_AWID(top_complex_fir_U0_m_axi_bundle1_AWID),
    .m_axi_bundle1_AWLEN(top_complex_fir_U0_m_axi_bundle1_AWLEN),
    .m_axi_bundle1_AWSIZE(top_complex_fir_U0_m_axi_bundle1_AWSIZE),
    .m_axi_bundle1_AWBURST(top_complex_fir_U0_m_axi_bundle1_AWBURST),
    .m_axi_bundle1_AWLOCK(top_complex_fir_U0_m_axi_bundle1_AWLOCK),
    .m_axi_bundle1_AWCACHE(top_complex_fir_U0_m_axi_bundle1_AWCACHE),
    .m_axi_bundle1_AWPROT(top_complex_fir_U0_m_axi_bundle1_AWPROT),
    .m_axi_bundle1_AWQOS(top_complex_fir_U0_m_axi_bundle1_AWQOS),
    .m_axi_bundle1_AWREGION(top_complex_fir_U0_m_axi_bundle1_AWREGION),
    .m_axi_bundle1_AWUSER(top_complex_fir_U0_m_axi_bundle1_AWUSER),
    .m_axi_bundle1_WVALID(top_complex_fir_U0_m_axi_bundle1_WVALID),
    .m_axi_bundle1_WREADY(1'b0),
    .m_axi_bundle1_WDATA(top_complex_fir_U0_m_axi_bundle1_WDATA),
    .m_axi_bundle1_WSTRB(top_complex_fir_U0_m_axi_bundle1_WSTRB),
    .m_axi_bundle1_WLAST(top_complex_fir_U0_m_axi_bundle1_WLAST),
    .m_axi_bundle1_WID(top_complex_fir_U0_m_axi_bundle1_WID),
    .m_axi_bundle1_WUSER(top_complex_fir_U0_m_axi_bundle1_WUSER),
    .m_axi_bundle1_ARVALID(top_complex_fir_U0_m_axi_bundle1_ARVALID),
    .m_axi_bundle1_ARREADY(bundle1_ARREADY),
    .m_axi_bundle1_ARADDR(top_complex_fir_U0_m_axi_bundle1_ARADDR),
    .m_axi_bundle1_ARID(top_complex_fir_U0_m_axi_bundle1_ARID),
    .m_axi_bundle1_ARLEN(top_complex_fir_U0_m_axi_bundle1_ARLEN),
    .m_axi_bundle1_ARSIZE(top_complex_fir_U0_m_axi_bundle1_ARSIZE),
    .m_axi_bundle1_ARBURST(top_complex_fir_U0_m_axi_bundle1_ARBURST),
    .m_axi_bundle1_ARLOCK(top_complex_fir_U0_m_axi_bundle1_ARLOCK),
    .m_axi_bundle1_ARCACHE(top_complex_fir_U0_m_axi_bundle1_ARCACHE),
    .m_axi_bundle1_ARPROT(top_complex_fir_U0_m_axi_bundle1_ARPROT),
    .m_axi_bundle1_ARQOS(top_complex_fir_U0_m_axi_bundle1_ARQOS),
    .m_axi_bundle1_ARREGION(top_complex_fir_U0_m_axi_bundle1_ARREGION),
    .m_axi_bundle1_ARUSER(top_complex_fir_U0_m_axi_bundle1_ARUSER),
    .m_axi_bundle1_RVALID(bundle1_RVALID),
    .m_axi_bundle1_RREADY(top_complex_fir_U0_m_axi_bundle1_RREADY),
    .m_axi_bundle1_RDATA(bundle1_RDATA),
    .m_axi_bundle1_RLAST(bundle1_RLAST),
    .m_axi_bundle1_RID(bundle1_RID),
    .m_axi_bundle1_RFIFONUM(bundle1_RFIFONUM),
    .m_axi_bundle1_RUSER(bundle1_RUSER),
    .m_axi_bundle1_RRESP(bundle1_RRESP),
    .m_axi_bundle1_BVALID(1'b0),
    .m_axi_bundle1_BREADY(top_complex_fir_U0_m_axi_bundle1_BREADY),
    .m_axi_bundle1_BRESP(2'd0),
    .m_axi_bundle1_BID(1'd0),
    .m_axi_bundle1_BUSER(1'd0),
    .input_real(input_real),
    .m_axi_bundle2_AWVALID(top_complex_fir_U0_m_axi_bundle2_AWVALID),
    .m_axi_bundle2_AWREADY(1'b0),
    .m_axi_bundle2_AWADDR(top_complex_fir_U0_m_axi_bundle2_AWADDR),
    .m_axi_bundle2_AWID(top_complex_fir_U0_m_axi_bundle2_AWID),
    .m_axi_bundle2_AWLEN(top_complex_fir_U0_m_axi_bundle2_AWLEN),
    .m_axi_bundle2_AWSIZE(top_complex_fir_U0_m_axi_bundle2_AWSIZE),
    .m_axi_bundle2_AWBURST(top_complex_fir_U0_m_axi_bundle2_AWBURST),
    .m_axi_bundle2_AWLOCK(top_complex_fir_U0_m_axi_bundle2_AWLOCK),
    .m_axi_bundle2_AWCACHE(top_complex_fir_U0_m_axi_bundle2_AWCACHE),
    .m_axi_bundle2_AWPROT(top_complex_fir_U0_m_axi_bundle2_AWPROT),
    .m_axi_bundle2_AWQOS(top_complex_fir_U0_m_axi_bundle2_AWQOS),
    .m_axi_bundle2_AWREGION(top_complex_fir_U0_m_axi_bundle2_AWREGION),
    .m_axi_bundle2_AWUSER(top_complex_fir_U0_m_axi_bundle2_AWUSER),
    .m_axi_bundle2_WVALID(top_complex_fir_U0_m_axi_bundle2_WVALID),
    .m_axi_bundle2_WREADY(1'b0),
    .m_axi_bundle2_WDATA(top_complex_fir_U0_m_axi_bundle2_WDATA),
    .m_axi_bundle2_WSTRB(top_complex_fir_U0_m_axi_bundle2_WSTRB),
    .m_axi_bundle2_WLAST(top_complex_fir_U0_m_axi_bundle2_WLAST),
    .m_axi_bundle2_WID(top_complex_fir_U0_m_axi_bundle2_WID),
    .m_axi_bundle2_WUSER(top_complex_fir_U0_m_axi_bundle2_WUSER),
    .m_axi_bundle2_ARVALID(top_complex_fir_U0_m_axi_bundle2_ARVALID),
    .m_axi_bundle2_ARREADY(bundle2_ARREADY),
    .m_axi_bundle2_ARADDR(top_complex_fir_U0_m_axi_bundle2_ARADDR),
    .m_axi_bundle2_ARID(top_complex_fir_U0_m_axi_bundle2_ARID),
    .m_axi_bundle2_ARLEN(top_complex_fir_U0_m_axi_bundle2_ARLEN),
    .m_axi_bundle2_ARSIZE(top_complex_fir_U0_m_axi_bundle2_ARSIZE),
    .m_axi_bundle2_ARBURST(top_complex_fir_U0_m_axi_bundle2_ARBURST),
    .m_axi_bundle2_ARLOCK(top_complex_fir_U0_m_axi_bundle2_ARLOCK),
    .m_axi_bundle2_ARCACHE(top_complex_fir_U0_m_axi_bundle2_ARCACHE),
    .m_axi_bundle2_ARPROT(top_complex_fir_U0_m_axi_bundle2_ARPROT),
    .m_axi_bundle2_ARQOS(top_complex_fir_U0_m_axi_bundle2_ARQOS),
    .m_axi_bundle2_ARREGION(top_complex_fir_U0_m_axi_bundle2_ARREGION),
    .m_axi_bundle2_ARUSER(top_complex_fir_U0_m_axi_bundle2_ARUSER),
    .m_axi_bundle2_RVALID(bundle2_RVALID),
    .m_axi_bundle2_RREADY(top_complex_fir_U0_m_axi_bundle2_RREADY),
    .m_axi_bundle2_RDATA(bundle2_RDATA),
    .m_axi_bundle2_RLAST(bundle2_RLAST),
    .m_axi_bundle2_RID(bundle2_RID),
    .m_axi_bundle2_RFIFONUM(bundle2_RFIFONUM),
    .m_axi_bundle2_RUSER(bundle2_RUSER),
    .m_axi_bundle2_RRESP(bundle2_RRESP),
    .m_axi_bundle2_BVALID(1'b0),
    .m_axi_bundle2_BREADY(top_complex_fir_U0_m_axi_bundle2_BREADY),
    .m_axi_bundle2_BRESP(2'd0),
    .m_axi_bundle2_BID(1'd0),
    .m_axi_bundle2_BUSER(1'd0),
    .input_img(input_img),
    .m_axi_bundle3_AWVALID(top_complex_fir_U0_m_axi_bundle3_AWVALID),
    .m_axi_bundle3_AWREADY(1'b0),
    .m_axi_bundle3_AWADDR(top_complex_fir_U0_m_axi_bundle3_AWADDR),
    .m_axi_bundle3_AWID(top_complex_fir_U0_m_axi_bundle3_AWID),
    .m_axi_bundle3_AWLEN(top_complex_fir_U0_m_axi_bundle3_AWLEN),
    .m_axi_bundle3_AWSIZE(top_complex_fir_U0_m_axi_bundle3_AWSIZE),
    .m_axi_bundle3_AWBURST(top_complex_fir_U0_m_axi_bundle3_AWBURST),
    .m_axi_bundle3_AWLOCK(top_complex_fir_U0_m_axi_bundle3_AWLOCK),
    .m_axi_bundle3_AWCACHE(top_complex_fir_U0_m_axi_bundle3_AWCACHE),
    .m_axi_bundle3_AWPROT(top_complex_fir_U0_m_axi_bundle3_AWPROT),
    .m_axi_bundle3_AWQOS(top_complex_fir_U0_m_axi_bundle3_AWQOS),
    .m_axi_bundle3_AWREGION(top_complex_fir_U0_m_axi_bundle3_AWREGION),
    .m_axi_bundle3_AWUSER(top_complex_fir_U0_m_axi_bundle3_AWUSER),
    .m_axi_bundle3_WVALID(top_complex_fir_U0_m_axi_bundle3_WVALID),
    .m_axi_bundle3_WREADY(1'b0),
    .m_axi_bundle3_WDATA(top_complex_fir_U0_m_axi_bundle3_WDATA),
    .m_axi_bundle3_WSTRB(top_complex_fir_U0_m_axi_bundle3_WSTRB),
    .m_axi_bundle3_WLAST(top_complex_fir_U0_m_axi_bundle3_WLAST),
    .m_axi_bundle3_WID(top_complex_fir_U0_m_axi_bundle3_WID),
    .m_axi_bundle3_WUSER(top_complex_fir_U0_m_axi_bundle3_WUSER),
    .m_axi_bundle3_ARVALID(top_complex_fir_U0_m_axi_bundle3_ARVALID),
    .m_axi_bundle3_ARREADY(bundle3_ARREADY),
    .m_axi_bundle3_ARADDR(top_complex_fir_U0_m_axi_bundle3_ARADDR),
    .m_axi_bundle3_ARID(top_complex_fir_U0_m_axi_bundle3_ARID),
    .m_axi_bundle3_ARLEN(top_complex_fir_U0_m_axi_bundle3_ARLEN),
    .m_axi_bundle3_ARSIZE(top_complex_fir_U0_m_axi_bundle3_ARSIZE),
    .m_axi_bundle3_ARBURST(top_complex_fir_U0_m_axi_bundle3_ARBURST),
    .m_axi_bundle3_ARLOCK(top_complex_fir_U0_m_axi_bundle3_ARLOCK),
    .m_axi_bundle3_ARCACHE(top_complex_fir_U0_m_axi_bundle3_ARCACHE),
    .m_axi_bundle3_ARPROT(top_complex_fir_U0_m_axi_bundle3_ARPROT),
    .m_axi_bundle3_ARQOS(top_complex_fir_U0_m_axi_bundle3_ARQOS),
    .m_axi_bundle3_ARREGION(top_complex_fir_U0_m_axi_bundle3_ARREGION),
    .m_axi_bundle3_ARUSER(top_complex_fir_U0_m_axi_bundle3_ARUSER),
    .m_axi_bundle3_RVALID(bundle3_RVALID),
    .m_axi_bundle3_RREADY(top_complex_fir_U0_m_axi_bundle3_RREADY),
    .m_axi_bundle3_RDATA(bundle3_RDATA),
    .m_axi_bundle3_RLAST(bundle3_RLAST),
    .m_axi_bundle3_RID(bundle3_RID),
    .m_axi_bundle3_RFIFONUM(bundle3_RFIFONUM),
    .m_axi_bundle3_RUSER(bundle3_RUSER),
    .m_axi_bundle3_RRESP(bundle3_RRESP),
    .m_axi_bundle3_BVALID(1'b0),
    .m_axi_bundle3_BREADY(top_complex_fir_U0_m_axi_bundle3_BREADY),
    .m_axi_bundle3_BRESP(2'd0),
    .m_axi_bundle3_BID(1'd0),
    .m_axi_bundle3_BUSER(1'd0),
    .kernel_real(kernel_real),
    .m_axi_bundle4_AWVALID(top_complex_fir_U0_m_axi_bundle4_AWVALID),
    .m_axi_bundle4_AWREADY(1'b0),
    .m_axi_bundle4_AWADDR(top_complex_fir_U0_m_axi_bundle4_AWADDR),
    .m_axi_bundle4_AWID(top_complex_fir_U0_m_axi_bundle4_AWID),
    .m_axi_bundle4_AWLEN(top_complex_fir_U0_m_axi_bundle4_AWLEN),
    .m_axi_bundle4_AWSIZE(top_complex_fir_U0_m_axi_bundle4_AWSIZE),
    .m_axi_bundle4_AWBURST(top_complex_fir_U0_m_axi_bundle4_AWBURST),
    .m_axi_bundle4_AWLOCK(top_complex_fir_U0_m_axi_bundle4_AWLOCK),
    .m_axi_bundle4_AWCACHE(top_complex_fir_U0_m_axi_bundle4_AWCACHE),
    .m_axi_bundle4_AWPROT(top_complex_fir_U0_m_axi_bundle4_AWPROT),
    .m_axi_bundle4_AWQOS(top_complex_fir_U0_m_axi_bundle4_AWQOS),
    .m_axi_bundle4_AWREGION(top_complex_fir_U0_m_axi_bundle4_AWREGION),
    .m_axi_bundle4_AWUSER(top_complex_fir_U0_m_axi_bundle4_AWUSER),
    .m_axi_bundle4_WVALID(top_complex_fir_U0_m_axi_bundle4_WVALID),
    .m_axi_bundle4_WREADY(1'b0),
    .m_axi_bundle4_WDATA(top_complex_fir_U0_m_axi_bundle4_WDATA),
    .m_axi_bundle4_WSTRB(top_complex_fir_U0_m_axi_bundle4_WSTRB),
    .m_axi_bundle4_WLAST(top_complex_fir_U0_m_axi_bundle4_WLAST),
    .m_axi_bundle4_WID(top_complex_fir_U0_m_axi_bundle4_WID),
    .m_axi_bundle4_WUSER(top_complex_fir_U0_m_axi_bundle4_WUSER),
    .m_axi_bundle4_ARVALID(top_complex_fir_U0_m_axi_bundle4_ARVALID),
    .m_axi_bundle4_ARREADY(bundle4_ARREADY),
    .m_axi_bundle4_ARADDR(top_complex_fir_U0_m_axi_bundle4_ARADDR),
    .m_axi_bundle4_ARID(top_complex_fir_U0_m_axi_bundle4_ARID),
    .m_axi_bundle4_ARLEN(top_complex_fir_U0_m_axi_bundle4_ARLEN),
    .m_axi_bundle4_ARSIZE(top_complex_fir_U0_m_axi_bundle4_ARSIZE),
    .m_axi_bundle4_ARBURST(top_complex_fir_U0_m_axi_bundle4_ARBURST),
    .m_axi_bundle4_ARLOCK(top_complex_fir_U0_m_axi_bundle4_ARLOCK),
    .m_axi_bundle4_ARCACHE(top_complex_fir_U0_m_axi_bundle4_ARCACHE),
    .m_axi_bundle4_ARPROT(top_complex_fir_U0_m_axi_bundle4_ARPROT),
    .m_axi_bundle4_ARQOS(top_complex_fir_U0_m_axi_bundle4_ARQOS),
    .m_axi_bundle4_ARREGION(top_complex_fir_U0_m_axi_bundle4_ARREGION),
    .m_axi_bundle4_ARUSER(top_complex_fir_U0_m_axi_bundle4_ARUSER),
    .m_axi_bundle4_RVALID(bundle4_RVALID),
    .m_axi_bundle4_RREADY(top_complex_fir_U0_m_axi_bundle4_RREADY),
    .m_axi_bundle4_RDATA(bundle4_RDATA),
    .m_axi_bundle4_RLAST(bundle4_RLAST),
    .m_axi_bundle4_RID(bundle4_RID),
    .m_axi_bundle4_RFIFONUM(bundle4_RFIFONUM),
    .m_axi_bundle4_RUSER(bundle4_RUSER),
    .m_axi_bundle4_RRESP(bundle4_RRESP),
    .m_axi_bundle4_BVALID(1'b0),
    .m_axi_bundle4_BREADY(top_complex_fir_U0_m_axi_bundle4_BREADY),
    .m_axi_bundle4_BRESP(2'd0),
    .m_axi_bundle4_BID(1'd0),
    .m_axi_bundle4_BUSER(1'd0),
    .kernel_img(kernel_img),
    .img_stream2_din(top_complex_fir_U0_img_stream2_din),
    .img_stream2_num_data_valid(img_stream_num_data_valid),
    .img_stream2_fifo_cap(img_stream_fifo_cap),
    .img_stream2_full_n(img_stream_full_n),
    .img_stream2_write(top_complex_fir_U0_img_stream2_write),
    .real_stream3_din(top_complex_fir_U0_real_stream3_din),
    .real_stream3_num_data_valid(real_stream_num_data_valid),
    .real_stream3_fifo_cap(real_stream_fifo_cap),
    .real_stream3_full_n(real_stream_full_n),
    .real_stream3_write(top_complex_fir_U0_real_stream3_write),
    .input_length(input_length),
    .input_length_c_din(top_complex_fir_U0_input_length_c_din),
    .input_length_c_num_data_valid(input_length_c_num_data_valid),
    .input_length_c_fifo_cap(input_length_c_fifo_cap),
    .input_length_c_full_n(input_length_c_full_n),
    .input_length_c_write(top_complex_fir_U0_input_length_c_write)
);

top_fpga417_top_cordic top_cordic_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(top_cordic_U0_ap_start),
    .ap_done(top_cordic_U0_ap_done),
    .ap_continue(top_cordic_U0_ap_continue),
    .ap_idle(top_cordic_U0_ap_idle),
    .ap_ready(top_cordic_U0_ap_ready),
    .img_stream2_dout(img_stream_dout),
    .img_stream2_num_data_valid(img_stream_num_data_valid),
    .img_stream2_fifo_cap(img_stream_fifo_cap),
    .img_stream2_empty_n(img_stream_empty_n),
    .img_stream2_read(top_cordic_U0_img_stream2_read),
    .real_stream3_dout(real_stream_dout),
    .real_stream3_num_data_valid(real_stream_num_data_valid),
    .real_stream3_fifo_cap(real_stream_fifo_cap),
    .real_stream3_empty_n(real_stream_empty_n),
    .real_stream3_read(top_cordic_U0_real_stream3_read),
    .m_axi_bundle5_AWVALID(top_cordic_U0_m_axi_bundle5_AWVALID),
    .m_axi_bundle5_AWREADY(bundle5_AWREADY),
    .m_axi_bundle5_AWADDR(top_cordic_U0_m_axi_bundle5_AWADDR),
    .m_axi_bundle5_AWID(top_cordic_U0_m_axi_bundle5_AWID),
    .m_axi_bundle5_AWLEN(top_cordic_U0_m_axi_bundle5_AWLEN),
    .m_axi_bundle5_AWSIZE(top_cordic_U0_m_axi_bundle5_AWSIZE),
    .m_axi_bundle5_AWBURST(top_cordic_U0_m_axi_bundle5_AWBURST),
    .m_axi_bundle5_AWLOCK(top_cordic_U0_m_axi_bundle5_AWLOCK),
    .m_axi_bundle5_AWCACHE(top_cordic_U0_m_axi_bundle5_AWCACHE),
    .m_axi_bundle5_AWPROT(top_cordic_U0_m_axi_bundle5_AWPROT),
    .m_axi_bundle5_AWQOS(top_cordic_U0_m_axi_bundle5_AWQOS),
    .m_axi_bundle5_AWREGION(top_cordic_U0_m_axi_bundle5_AWREGION),
    .m_axi_bundle5_AWUSER(top_cordic_U0_m_axi_bundle5_AWUSER),
    .m_axi_bundle5_WVALID(top_cordic_U0_m_axi_bundle5_WVALID),
    .m_axi_bundle5_WREADY(bundle5_WREADY),
    .m_axi_bundle5_WDATA(top_cordic_U0_m_axi_bundle5_WDATA),
    .m_axi_bundle5_WSTRB(top_cordic_U0_m_axi_bundle5_WSTRB),
    .m_axi_bundle5_WLAST(top_cordic_U0_m_axi_bundle5_WLAST),
    .m_axi_bundle5_WID(top_cordic_U0_m_axi_bundle5_WID),
    .m_axi_bundle5_WUSER(top_cordic_U0_m_axi_bundle5_WUSER),
    .m_axi_bundle5_ARVALID(top_cordic_U0_m_axi_bundle5_ARVALID),
    .m_axi_bundle5_ARREADY(1'b0),
    .m_axi_bundle5_ARADDR(top_cordic_U0_m_axi_bundle5_ARADDR),
    .m_axi_bundle5_ARID(top_cordic_U0_m_axi_bundle5_ARID),
    .m_axi_bundle5_ARLEN(top_cordic_U0_m_axi_bundle5_ARLEN),
    .m_axi_bundle5_ARSIZE(top_cordic_U0_m_axi_bundle5_ARSIZE),
    .m_axi_bundle5_ARBURST(top_cordic_U0_m_axi_bundle5_ARBURST),
    .m_axi_bundle5_ARLOCK(top_cordic_U0_m_axi_bundle5_ARLOCK),
    .m_axi_bundle5_ARCACHE(top_cordic_U0_m_axi_bundle5_ARCACHE),
    .m_axi_bundle5_ARPROT(top_cordic_U0_m_axi_bundle5_ARPROT),
    .m_axi_bundle5_ARQOS(top_cordic_U0_m_axi_bundle5_ARQOS),
    .m_axi_bundle5_ARREGION(top_cordic_U0_m_axi_bundle5_ARREGION),
    .m_axi_bundle5_ARUSER(top_cordic_U0_m_axi_bundle5_ARUSER),
    .m_axi_bundle5_RVALID(1'b0),
    .m_axi_bundle5_RREADY(top_cordic_U0_m_axi_bundle5_RREADY),
    .m_axi_bundle5_RDATA(32'd0),
    .m_axi_bundle5_RLAST(1'b0),
    .m_axi_bundle5_RID(1'd0),
    .m_axi_bundle5_RFIFONUM(9'd0),
    .m_axi_bundle5_RUSER(1'd0),
    .m_axi_bundle5_RRESP(2'd0),
    .m_axi_bundle5_BVALID(bundle5_BVALID),
    .m_axi_bundle5_BREADY(top_cordic_U0_m_axi_bundle5_BREADY),
    .m_axi_bundle5_BRESP(bundle5_BRESP),
    .m_axi_bundle5_BID(bundle5_BID),
    .m_axi_bundle5_BUSER(bundle5_BUSER),
    .output_mag_dout(output_mag_c_dout),
    .output_mag_num_data_valid(output_mag_c_num_data_valid),
    .output_mag_fifo_cap(output_mag_c_fifo_cap),
    .output_mag_empty_n(output_mag_c_empty_n),
    .output_mag_read(top_cordic_U0_output_mag_read),
    .m_axi_bundle6_AWVALID(top_cordic_U0_m_axi_bundle6_AWVALID),
    .m_axi_bundle6_AWREADY(bundle6_AWREADY),
    .m_axi_bundle6_AWADDR(top_cordic_U0_m_axi_bundle6_AWADDR),
    .m_axi_bundle6_AWID(top_cordic_U0_m_axi_bundle6_AWID),
    .m_axi_bundle6_AWLEN(top_cordic_U0_m_axi_bundle6_AWLEN),
    .m_axi_bundle6_AWSIZE(top_cordic_U0_m_axi_bundle6_AWSIZE),
    .m_axi_bundle6_AWBURST(top_cordic_U0_m_axi_bundle6_AWBURST),
    .m_axi_bundle6_AWLOCK(top_cordic_U0_m_axi_bundle6_AWLOCK),
    .m_axi_bundle6_AWCACHE(top_cordic_U0_m_axi_bundle6_AWCACHE),
    .m_axi_bundle6_AWPROT(top_cordic_U0_m_axi_bundle6_AWPROT),
    .m_axi_bundle6_AWQOS(top_cordic_U0_m_axi_bundle6_AWQOS),
    .m_axi_bundle6_AWREGION(top_cordic_U0_m_axi_bundle6_AWREGION),
    .m_axi_bundle6_AWUSER(top_cordic_U0_m_axi_bundle6_AWUSER),
    .m_axi_bundle6_WVALID(top_cordic_U0_m_axi_bundle6_WVALID),
    .m_axi_bundle6_WREADY(bundle6_WREADY),
    .m_axi_bundle6_WDATA(top_cordic_U0_m_axi_bundle6_WDATA),
    .m_axi_bundle6_WSTRB(top_cordic_U0_m_axi_bundle6_WSTRB),
    .m_axi_bundle6_WLAST(top_cordic_U0_m_axi_bundle6_WLAST),
    .m_axi_bundle6_WID(top_cordic_U0_m_axi_bundle6_WID),
    .m_axi_bundle6_WUSER(top_cordic_U0_m_axi_bundle6_WUSER),
    .m_axi_bundle6_ARVALID(top_cordic_U0_m_axi_bundle6_ARVALID),
    .m_axi_bundle6_ARREADY(1'b0),
    .m_axi_bundle6_ARADDR(top_cordic_U0_m_axi_bundle6_ARADDR),
    .m_axi_bundle6_ARID(top_cordic_U0_m_axi_bundle6_ARID),
    .m_axi_bundle6_ARLEN(top_cordic_U0_m_axi_bundle6_ARLEN),
    .m_axi_bundle6_ARSIZE(top_cordic_U0_m_axi_bundle6_ARSIZE),
    .m_axi_bundle6_ARBURST(top_cordic_U0_m_axi_bundle6_ARBURST),
    .m_axi_bundle6_ARLOCK(top_cordic_U0_m_axi_bundle6_ARLOCK),
    .m_axi_bundle6_ARCACHE(top_cordic_U0_m_axi_bundle6_ARCACHE),
    .m_axi_bundle6_ARPROT(top_cordic_U0_m_axi_bundle6_ARPROT),
    .m_axi_bundle6_ARQOS(top_cordic_U0_m_axi_bundle6_ARQOS),
    .m_axi_bundle6_ARREGION(top_cordic_U0_m_axi_bundle6_ARREGION),
    .m_axi_bundle6_ARUSER(top_cordic_U0_m_axi_bundle6_ARUSER),
    .m_axi_bundle6_RVALID(1'b0),
    .m_axi_bundle6_RREADY(top_cordic_U0_m_axi_bundle6_RREADY),
    .m_axi_bundle6_RDATA(32'd0),
    .m_axi_bundle6_RLAST(1'b0),
    .m_axi_bundle6_RID(1'd0),
    .m_axi_bundle6_RFIFONUM(9'd0),
    .m_axi_bundle6_RUSER(1'd0),
    .m_axi_bundle6_RRESP(2'd0),
    .m_axi_bundle6_BVALID(bundle6_BVALID),
    .m_axi_bundle6_BREADY(top_cordic_U0_m_axi_bundle6_BREADY),
    .m_axi_bundle6_BRESP(bundle6_BRESP),
    .m_axi_bundle6_BID(bundle6_BID),
    .m_axi_bundle6_BUSER(bundle6_BUSER),
    .output_theta_dout(output_theta_c_dout),
    .output_theta_num_data_valid(output_theta_c_num_data_valid),
    .output_theta_fifo_cap(output_theta_c_fifo_cap),
    .output_theta_empty_n(output_theta_c_empty_n),
    .output_theta_read(top_cordic_U0_output_theta_read),
    .input_length_dout(input_length_c_dout),
    .input_length_num_data_valid(input_length_c_num_data_valid),
    .input_length_fifo_cap(input_length_c_fifo_cap),
    .input_length_empty_n(input_length_c_empty_n),
    .input_length_read(top_cordic_U0_input_length_read)
);

top_fpga417_fifo_w64_d3_S output_mag_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_output_mag_c_din),
    .if_full_n(output_mag_c_full_n),
    .if_write(entry_proc_U0_output_mag_c_write),
    .if_dout(output_mag_c_dout),
    .if_num_data_valid(output_mag_c_num_data_valid),
    .if_fifo_cap(output_mag_c_fifo_cap),
    .if_empty_n(output_mag_c_empty_n),
    .if_read(top_cordic_U0_output_mag_read)
);

top_fpga417_fifo_w64_d3_S output_theta_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_output_theta_c_din),
    .if_full_n(output_theta_c_full_n),
    .if_write(entry_proc_U0_output_theta_c_write),
    .if_dout(output_theta_c_dout),
    .if_num_data_valid(output_theta_c_num_data_valid),
    .if_fifo_cap(output_theta_c_fifo_cap),
    .if_empty_n(output_theta_c_empty_n),
    .if_read(top_cordic_U0_output_theta_read)
);

top_fpga417_fifo_w32_d2_S img_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(top_complex_fir_U0_img_stream2_din),
    .if_full_n(img_stream_full_n),
    .if_write(top_complex_fir_U0_img_stream2_write),
    .if_dout(img_stream_dout),
    .if_num_data_valid(img_stream_num_data_valid),
    .if_fifo_cap(img_stream_fifo_cap),
    .if_empty_n(img_stream_empty_n),
    .if_read(top_cordic_U0_img_stream2_read)
);

top_fpga417_fifo_w32_d2_S real_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(top_complex_fir_U0_real_stream3_din),
    .if_full_n(real_stream_full_n),
    .if_write(top_complex_fir_U0_real_stream3_write),
    .if_dout(real_stream_dout),
    .if_num_data_valid(real_stream_num_data_valid),
    .if_fifo_cap(real_stream_fifo_cap),
    .if_empty_n(real_stream_empty_n),
    .if_read(top_cordic_U0_real_stream3_read)
);

top_fpga417_fifo_w32_d2_S input_length_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(top_complex_fir_U0_input_length_c_din),
    .if_full_n(input_length_c_full_n),
    .if_write(top_complex_fir_U0_input_length_c_write),
    .if_dout(input_length_c_dout),
    .if_num_data_valid(input_length_c_num_data_valid),
    .if_fifo_cap(input_length_c_fifo_cap),
    .if_empty_n(input_length_c_empty_n),
    .if_read(top_cordic_U0_input_length_read)
);

top_fpga417_start_for_top_cordic_U0 start_for_top_cordic_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_top_cordic_U0_din),
    .if_full_n(start_for_top_cordic_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_top_cordic_U0_dout),
    .if_empty_n(start_for_top_cordic_U0_empty_n),
    .if_read(top_cordic_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_top_complex_fir_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_top_complex_fir_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_top_complex_fir_U0_ap_ready <= ap_sync_top_complex_fir_U0_ap_ready;
        end
    end
end

assign ap_done = top_cordic_U0_ap_done;

assign ap_idle = (top_cordic_U0_ap_idle & top_complex_fir_U0_ap_idle & entry_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_top_complex_fir_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign ap_sync_top_complex_fir_U0_ap_ready = (top_complex_fir_U0_ap_ready | ap_sync_reg_top_complex_fir_U0_ap_ready);

assign bundle1_RID = 1'd0;

assign bundle1_RLAST = 1'b0;

assign bundle1_RRESP = 2'd0;

assign bundle1_RUSER = 1'd0;

assign bundle2_RID = 1'd0;

assign bundle2_RLAST = 1'b0;

assign bundle2_RRESP = 2'd0;

assign bundle2_RUSER = 1'd0;

assign bundle3_RID = 1'd0;

assign bundle3_RLAST = 1'b0;

assign bundle3_RRESP = 2'd0;

assign bundle3_RUSER = 1'd0;

assign bundle4_RID = 1'd0;

assign bundle4_RLAST = 1'b0;

assign bundle4_RRESP = 2'd0;

assign bundle4_RUSER = 1'd0;

assign bundle5_BID = 1'd0;

assign bundle5_BRESP = 2'd0;

assign bundle5_BUSER = 1'd0;

assign bundle6_BID = 1'd0;

assign bundle6_BRESP = 2'd0;

assign bundle6_BUSER = 1'd0;

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign start_for_top_cordic_U0_din = 1'b1;

assign top_complex_fir_U0_ap_continue = 1'b1;

assign top_complex_fir_U0_ap_start = ((ap_sync_reg_top_complex_fir_U0_ap_ready ^ 1'b1) & ap_start);

assign top_cordic_U0_ap_continue = 1'b1;

assign top_cordic_U0_ap_start = start_for_top_cordic_U0_empty_n;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "top_fpga417_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //top_fpga417

