-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2022.2 (win64) Build 3671981 Fri Oct 14 05:00:03 MDT 2022
-- Date        : Thu Apr 25 22:08:57 2024
-- Host        : E5-CSE-136-19 running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               d:/cmpen_417_final_part3/cmpen_417_final_part3.gen/sources_1/bd/design_1/ip/design_1_top_fpga417_0_0_1/design_1_top_fpga417_0_0_stub.vhdl
-- Design      : design_1_top_fpga417_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg484-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity design_1_top_fpga417_0_0 is
  Port ( 
    s_axi_bundle8_AWADDR : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_bundle8_AWVALID : in STD_LOGIC;
    s_axi_bundle8_AWREADY : out STD_LOGIC;
    s_axi_bundle8_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_bundle8_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_bundle8_WVALID : in STD_LOGIC;
    s_axi_bundle8_WREADY : out STD_LOGIC;
    s_axi_bundle8_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_bundle8_BVALID : out STD_LOGIC;
    s_axi_bundle8_BREADY : in STD_LOGIC;
    s_axi_bundle8_ARADDR : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_bundle8_ARVALID : in STD_LOGIC;
    s_axi_bundle8_ARREADY : out STD_LOGIC;
    s_axi_bundle8_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_bundle8_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_bundle8_RVALID : out STD_LOGIC;
    s_axi_bundle8_RREADY : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_RREADY : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_bundle1_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle1_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle1_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle1_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle1_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle1_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle1_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle1_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle1_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle1_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle1_AWVALID : out STD_LOGIC;
    m_axi_bundle1_AWREADY : in STD_LOGIC;
    m_axi_bundle1_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle1_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle1_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle1_WLAST : out STD_LOGIC;
    m_axi_bundle1_WVALID : out STD_LOGIC;
    m_axi_bundle1_WREADY : in STD_LOGIC;
    m_axi_bundle1_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle1_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle1_BVALID : in STD_LOGIC;
    m_axi_bundle1_BREADY : out STD_LOGIC;
    m_axi_bundle1_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle1_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle1_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle1_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle1_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle1_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle1_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle1_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle1_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle1_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle1_ARVALID : out STD_LOGIC;
    m_axi_bundle1_ARREADY : in STD_LOGIC;
    m_axi_bundle1_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle1_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle1_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle1_RLAST : in STD_LOGIC;
    m_axi_bundle1_RVALID : in STD_LOGIC;
    m_axi_bundle1_RREADY : out STD_LOGIC;
    m_axi_bundle2_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle2_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle2_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle2_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle2_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle2_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle2_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle2_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle2_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle2_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle2_AWVALID : out STD_LOGIC;
    m_axi_bundle2_AWREADY : in STD_LOGIC;
    m_axi_bundle2_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle2_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle2_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle2_WLAST : out STD_LOGIC;
    m_axi_bundle2_WVALID : out STD_LOGIC;
    m_axi_bundle2_WREADY : in STD_LOGIC;
    m_axi_bundle2_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle2_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle2_BVALID : in STD_LOGIC;
    m_axi_bundle2_BREADY : out STD_LOGIC;
    m_axi_bundle2_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle2_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle2_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle2_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle2_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle2_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle2_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle2_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle2_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle2_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle2_ARVALID : out STD_LOGIC;
    m_axi_bundle2_ARREADY : in STD_LOGIC;
    m_axi_bundle2_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle2_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle2_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle2_RLAST : in STD_LOGIC;
    m_axi_bundle2_RVALID : in STD_LOGIC;
    m_axi_bundle2_RREADY : out STD_LOGIC;
    m_axi_bundle3_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle3_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle3_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle3_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle3_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle3_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle3_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle3_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle3_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle3_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle3_AWVALID : out STD_LOGIC;
    m_axi_bundle3_AWREADY : in STD_LOGIC;
    m_axi_bundle3_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle3_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle3_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle3_WLAST : out STD_LOGIC;
    m_axi_bundle3_WVALID : out STD_LOGIC;
    m_axi_bundle3_WREADY : in STD_LOGIC;
    m_axi_bundle3_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle3_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle3_BVALID : in STD_LOGIC;
    m_axi_bundle3_BREADY : out STD_LOGIC;
    m_axi_bundle3_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle3_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle3_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle3_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle3_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle3_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle3_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle3_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle3_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle3_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle3_ARVALID : out STD_LOGIC;
    m_axi_bundle3_ARREADY : in STD_LOGIC;
    m_axi_bundle3_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle3_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle3_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle3_RLAST : in STD_LOGIC;
    m_axi_bundle3_RVALID : in STD_LOGIC;
    m_axi_bundle3_RREADY : out STD_LOGIC;
    m_axi_bundle4_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle4_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle4_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle4_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle4_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle4_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle4_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle4_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle4_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle4_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle4_AWVALID : out STD_LOGIC;
    m_axi_bundle4_AWREADY : in STD_LOGIC;
    m_axi_bundle4_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle4_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle4_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle4_WLAST : out STD_LOGIC;
    m_axi_bundle4_WVALID : out STD_LOGIC;
    m_axi_bundle4_WREADY : in STD_LOGIC;
    m_axi_bundle4_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle4_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle4_BVALID : in STD_LOGIC;
    m_axi_bundle4_BREADY : out STD_LOGIC;
    m_axi_bundle4_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle4_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle4_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle4_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle4_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle4_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle4_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle4_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle4_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle4_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle4_ARVALID : out STD_LOGIC;
    m_axi_bundle4_ARREADY : in STD_LOGIC;
    m_axi_bundle4_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle4_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle4_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle4_RLAST : in STD_LOGIC;
    m_axi_bundle4_RVALID : in STD_LOGIC;
    m_axi_bundle4_RREADY : out STD_LOGIC;
    m_axi_bundle5_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle5_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle5_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle5_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle5_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle5_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle5_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle5_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle5_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle5_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle5_AWVALID : out STD_LOGIC;
    m_axi_bundle5_AWREADY : in STD_LOGIC;
    m_axi_bundle5_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle5_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle5_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle5_WLAST : out STD_LOGIC;
    m_axi_bundle5_WVALID : out STD_LOGIC;
    m_axi_bundle5_WREADY : in STD_LOGIC;
    m_axi_bundle5_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle5_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle5_BVALID : in STD_LOGIC;
    m_axi_bundle5_BREADY : out STD_LOGIC;
    m_axi_bundle5_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle5_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle5_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle5_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle5_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle5_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle5_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle5_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle5_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle5_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle5_ARVALID : out STD_LOGIC;
    m_axi_bundle5_ARREADY : in STD_LOGIC;
    m_axi_bundle5_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle5_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle5_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle5_RLAST : in STD_LOGIC;
    m_axi_bundle5_RVALID : in STD_LOGIC;
    m_axi_bundle5_RREADY : out STD_LOGIC;
    m_axi_bundle6_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle6_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle6_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle6_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle6_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle6_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle6_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle6_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle6_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle6_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle6_AWVALID : out STD_LOGIC;
    m_axi_bundle6_AWREADY : in STD_LOGIC;
    m_axi_bundle6_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle6_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle6_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle6_WLAST : out STD_LOGIC;
    m_axi_bundle6_WVALID : out STD_LOGIC;
    m_axi_bundle6_WREADY : in STD_LOGIC;
    m_axi_bundle6_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle6_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle6_BVALID : in STD_LOGIC;
    m_axi_bundle6_BREADY : out STD_LOGIC;
    m_axi_bundle6_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle6_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_bundle6_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_bundle6_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle6_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle6_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle6_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle6_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle6_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_bundle6_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_bundle6_ARVALID : out STD_LOGIC;
    m_axi_bundle6_ARREADY : in STD_LOGIC;
    m_axi_bundle6_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_bundle6_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_bundle6_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bundle6_RLAST : in STD_LOGIC;
    m_axi_bundle6_RVALID : in STD_LOGIC;
    m_axi_bundle6_RREADY : out STD_LOGIC;
    input_length : in STD_LOGIC_VECTOR ( 31 downto 0 )
  );

end design_1_top_fpga417_0_0;

architecture stub of design_1_top_fpga417_0_0 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "s_axi_bundle8_AWADDR[3:0],s_axi_bundle8_AWVALID,s_axi_bundle8_AWREADY,s_axi_bundle8_WDATA[31:0],s_axi_bundle8_WSTRB[3:0],s_axi_bundle8_WVALID,s_axi_bundle8_WREADY,s_axi_bundle8_BRESP[1:0],s_axi_bundle8_BVALID,s_axi_bundle8_BREADY,s_axi_bundle8_ARADDR[3:0],s_axi_bundle8_ARVALID,s_axi_bundle8_ARREADY,s_axi_bundle8_RDATA[31:0],s_axi_bundle8_RRESP[1:0],s_axi_bundle8_RVALID,s_axi_bundle8_RREADY,s_axi_control_AWADDR[6:0],s_axi_control_AWVALID,s_axi_control_AWREADY,s_axi_control_WDATA[31:0],s_axi_control_WSTRB[3:0],s_axi_control_WVALID,s_axi_control_WREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_BREADY,s_axi_control_ARADDR[6:0],s_axi_control_ARVALID,s_axi_control_ARREADY,s_axi_control_RDATA[31:0],s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_RREADY,ap_clk,ap_rst_n,interrupt,m_axi_bundle1_AWID[0:0],m_axi_bundle1_AWADDR[63:0],m_axi_bundle1_AWLEN[7:0],m_axi_bundle1_AWSIZE[2:0],m_axi_bundle1_AWBURST[1:0],m_axi_bundle1_AWLOCK[1:0],m_axi_bundle1_AWREGION[3:0],m_axi_bundle1_AWCACHE[3:0],m_axi_bundle1_AWPROT[2:0],m_axi_bundle1_AWQOS[3:0],m_axi_bundle1_AWVALID,m_axi_bundle1_AWREADY,m_axi_bundle1_WID[0:0],m_axi_bundle1_WDATA[31:0],m_axi_bundle1_WSTRB[3:0],m_axi_bundle1_WLAST,m_axi_bundle1_WVALID,m_axi_bundle1_WREADY,m_axi_bundle1_BID[0:0],m_axi_bundle1_BRESP[1:0],m_axi_bundle1_BVALID,m_axi_bundle1_BREADY,m_axi_bundle1_ARID[0:0],m_axi_bundle1_ARADDR[63:0],m_axi_bundle1_ARLEN[7:0],m_axi_bundle1_ARSIZE[2:0],m_axi_bundle1_ARBURST[1:0],m_axi_bundle1_ARLOCK[1:0],m_axi_bundle1_ARREGION[3:0],m_axi_bundle1_ARCACHE[3:0],m_axi_bundle1_ARPROT[2:0],m_axi_bundle1_ARQOS[3:0],m_axi_bundle1_ARVALID,m_axi_bundle1_ARREADY,m_axi_bundle1_RID[0:0],m_axi_bundle1_RDATA[31:0],m_axi_bundle1_RRESP[1:0],m_axi_bundle1_RLAST,m_axi_bundle1_RVALID,m_axi_bundle1_RREADY,m_axi_bundle2_AWID[0:0],m_axi_bundle2_AWADDR[63:0],m_axi_bundle2_AWLEN[7:0],m_axi_bundle2_AWSIZE[2:0],m_axi_bundle2_AWBURST[1:0],m_axi_bundle2_AWLOCK[1:0],m_axi_bundle2_AWREGION[3:0],m_axi_bundle2_AWCACHE[3:0],m_axi_bundle2_AWPROT[2:0],m_axi_bundle2_AWQOS[3:0],m_axi_bundle2_AWVALID,m_axi_bundle2_AWREADY,m_axi_bundle2_WID[0:0],m_axi_bundle2_WDATA[31:0],m_axi_bundle2_WSTRB[3:0],m_axi_bundle2_WLAST,m_axi_bundle2_WVALID,m_axi_bundle2_WREADY,m_axi_bundle2_BID[0:0],m_axi_bundle2_BRESP[1:0],m_axi_bundle2_BVALID,m_axi_bundle2_BREADY,m_axi_bundle2_ARID[0:0],m_axi_bundle2_ARADDR[63:0],m_axi_bundle2_ARLEN[7:0],m_axi_bundle2_ARSIZE[2:0],m_axi_bundle2_ARBURST[1:0],m_axi_bundle2_ARLOCK[1:0],m_axi_bundle2_ARREGION[3:0],m_axi_bundle2_ARCACHE[3:0],m_axi_bundle2_ARPROT[2:0],m_axi_bundle2_ARQOS[3:0],m_axi_bundle2_ARVALID,m_axi_bundle2_ARREADY,m_axi_bundle2_RID[0:0],m_axi_bundle2_RDATA[31:0],m_axi_bundle2_RRESP[1:0],m_axi_bundle2_RLAST,m_axi_bundle2_RVALID,m_axi_bundle2_RREADY,m_axi_bundle3_AWID[0:0],m_axi_bundle3_AWADDR[63:0],m_axi_bundle3_AWLEN[7:0],m_axi_bundle3_AWSIZE[2:0],m_axi_bundle3_AWBURST[1:0],m_axi_bundle3_AWLOCK[1:0],m_axi_bundle3_AWREGION[3:0],m_axi_bundle3_AWCACHE[3:0],m_axi_bundle3_AWPROT[2:0],m_axi_bundle3_AWQOS[3:0],m_axi_bundle3_AWVALID,m_axi_bundle3_AWREADY,m_axi_bundle3_WID[0:0],m_axi_bundle3_WDATA[31:0],m_axi_bundle3_WSTRB[3:0],m_axi_bundle3_WLAST,m_axi_bundle3_WVALID,m_axi_bundle3_WREADY,m_axi_bundle3_BID[0:0],m_axi_bundle3_BRESP[1:0],m_axi_bundle3_BVALID,m_axi_bundle3_BREADY,m_axi_bundle3_ARID[0:0],m_axi_bundle3_ARADDR[63:0],m_axi_bundle3_ARLEN[7:0],m_axi_bundle3_ARSIZE[2:0],m_axi_bundle3_ARBURST[1:0],m_axi_bundle3_ARLOCK[1:0],m_axi_bundle3_ARREGION[3:0],m_axi_bundle3_ARCACHE[3:0],m_axi_bundle3_ARPROT[2:0],m_axi_bundle3_ARQOS[3:0],m_axi_bundle3_ARVALID,m_axi_bundle3_ARREADY,m_axi_bundle3_RID[0:0],m_axi_bundle3_RDATA[31:0],m_axi_bundle3_RRESP[1:0],m_axi_bundle3_RLAST,m_axi_bundle3_RVALID,m_axi_bundle3_RREADY,m_axi_bundle4_AWID[0:0],m_axi_bundle4_AWADDR[63:0],m_axi_bundle4_AWLEN[7:0],m_axi_bundle4_AWSIZE[2:0],m_axi_bundle4_AWBURST[1:0],m_axi_bundle4_AWLOCK[1:0],m_axi_bundle4_AWREGION[3:0],m_axi_bundle4_AWCACHE[3:0],m_axi_bundle4_AWPROT[2:0],m_axi_bundle4_AWQOS[3:0],m_axi_bundle4_AWVALID,m_axi_bundle4_AWREADY,m_axi_bundle4_WID[0:0],m_axi_bundle4_WDATA[31:0],m_axi_bundle4_WSTRB[3:0],m_axi_bundle4_WLAST,m_axi_bundle4_WVALID,m_axi_bundle4_WREADY,m_axi_bundle4_BID[0:0],m_axi_bundle4_BRESP[1:0],m_axi_bundle4_BVALID,m_axi_bundle4_BREADY,m_axi_bundle4_ARID[0:0],m_axi_bundle4_ARADDR[63:0],m_axi_bundle4_ARLEN[7:0],m_axi_bundle4_ARSIZE[2:0],m_axi_bundle4_ARBURST[1:0],m_axi_bundle4_ARLOCK[1:0],m_axi_bundle4_ARREGION[3:0],m_axi_bundle4_ARCACHE[3:0],m_axi_bundle4_ARPROT[2:0],m_axi_bundle4_ARQOS[3:0],m_axi_bundle4_ARVALID,m_axi_bundle4_ARREADY,m_axi_bundle4_RID[0:0],m_axi_bundle4_RDATA[31:0],m_axi_bundle4_RRESP[1:0],m_axi_bundle4_RLAST,m_axi_bundle4_RVALID,m_axi_bundle4_RREADY,m_axi_bundle5_AWID[0:0],m_axi_bundle5_AWADDR[63:0],m_axi_bundle5_AWLEN[7:0],m_axi_bundle5_AWSIZE[2:0],m_axi_bundle5_AWBURST[1:0],m_axi_bundle5_AWLOCK[1:0],m_axi_bundle5_AWREGION[3:0],m_axi_bundle5_AWCACHE[3:0],m_axi_bundle5_AWPROT[2:0],m_axi_bundle5_AWQOS[3:0],m_axi_bundle5_AWVALID,m_axi_bundle5_AWREADY,m_axi_bundle5_WID[0:0],m_axi_bundle5_WDATA[31:0],m_axi_bundle5_WSTRB[3:0],m_axi_bundle5_WLAST,m_axi_bundle5_WVALID,m_axi_bundle5_WREADY,m_axi_bundle5_BID[0:0],m_axi_bundle5_BRESP[1:0],m_axi_bundle5_BVALID,m_axi_bundle5_BREADY,m_axi_bundle5_ARID[0:0],m_axi_bundle5_ARADDR[63:0],m_axi_bundle5_ARLEN[7:0],m_axi_bundle5_ARSIZE[2:0],m_axi_bundle5_ARBURST[1:0],m_axi_bundle5_ARLOCK[1:0],m_axi_bundle5_ARREGION[3:0],m_axi_bundle5_ARCACHE[3:0],m_axi_bundle5_ARPROT[2:0],m_axi_bundle5_ARQOS[3:0],m_axi_bundle5_ARVALID,m_axi_bundle5_ARREADY,m_axi_bundle5_RID[0:0],m_axi_bundle5_RDATA[31:0],m_axi_bundle5_RRESP[1:0],m_axi_bundle5_RLAST,m_axi_bundle5_RVALID,m_axi_bundle5_RREADY,m_axi_bundle6_AWID[0:0],m_axi_bundle6_AWADDR[63:0],m_axi_bundle6_AWLEN[7:0],m_axi_bundle6_AWSIZE[2:0],m_axi_bundle6_AWBURST[1:0],m_axi_bundle6_AWLOCK[1:0],m_axi_bundle6_AWREGION[3:0],m_axi_bundle6_AWCACHE[3:0],m_axi_bundle6_AWPROT[2:0],m_axi_bundle6_AWQOS[3:0],m_axi_bundle6_AWVALID,m_axi_bundle6_AWREADY,m_axi_bundle6_WID[0:0],m_axi_bundle6_WDATA[31:0],m_axi_bundle6_WSTRB[3:0],m_axi_bundle6_WLAST,m_axi_bundle6_WVALID,m_axi_bundle6_WREADY,m_axi_bundle6_BID[0:0],m_axi_bundle6_BRESP[1:0],m_axi_bundle6_BVALID,m_axi_bundle6_BREADY,m_axi_bundle6_ARID[0:0],m_axi_bundle6_ARADDR[63:0],m_axi_bundle6_ARLEN[7:0],m_axi_bundle6_ARSIZE[2:0],m_axi_bundle6_ARBURST[1:0],m_axi_bundle6_ARLOCK[1:0],m_axi_bundle6_ARREGION[3:0],m_axi_bundle6_ARCACHE[3:0],m_axi_bundle6_ARPROT[2:0],m_axi_bundle6_ARQOS[3:0],m_axi_bundle6_ARVALID,m_axi_bundle6_ARREADY,m_axi_bundle6_RID[0:0],m_axi_bundle6_RDATA[31:0],m_axi_bundle6_RRESP[1:0],m_axi_bundle6_RLAST,m_axi_bundle6_RVALID,m_axi_bundle6_RREADY,input_length[31:0]";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "top_fpga417,Vivado 2022.2";
begin
end;
